#include <cstddef>
#include <cstdint>

#include <gbaemu/gba/cpu.hpp>
#include <gbaemu/gba/cpu/decoder.hpp>
#include <gbaemu/gba/cpu/decoder/arm.hpp>
#include <gbaemu/gba/cpu/impl/branch.hpp>
#include <gbaemu/gba/cpu/impl/dataproc.hpp>
#include <gbaemu/gba/cpu/impl/sdt.hpp>
#include <gbaemu/gba/cpu/impl/swi.hpp>

#define REP2(x) x, x
#define REP4(x) REP2(x), REP2(x)
#define REP8(x) REP4(x), REP4(x)
#define REP16(x) REP8(x), REP8(x)
#define REP32(x) REP16(x), REP16(x)
#define REP64(x) REP32(x), REP32(x)
#define REP128(x) REP64(x), REP64(x)
#define REP256(x) REP128(x), REP128(x)

namespace gbaemu::gba::cpu::decoder::arm {
    const opcodeCallback_t opcodeDecoderTable[] = {
        gbaemu::gba::cpu::impl::dataproc::opcode_and_LSL_Rm_0, // 0x000
        gbaemu::gba::cpu::impl::dataproc::opcode_and_LSL_Rm_1, // 0x001
        gbaemu::gba::cpu::impl::dataproc::opcode_and_LSR_Rm_0, // 0x002
        gbaemu::gba::cpu::impl::dataproc::opcode_and_LSR_Rm_1, // 0x003
        gbaemu::gba::cpu::impl::dataproc::opcode_and_ASR_Rm_0, // 0x004
        gbaemu::gba::cpu::impl::dataproc::opcode_and_ASR_Rm_1, // 0x005
        gbaemu::gba::cpu::impl::dataproc::opcode_and_ROR_Rm_0, // 0x006
        gbaemu::gba::cpu::impl::dataproc::opcode_and_ROR_Rm_1, // 0x007
        gbaemu::gba::cpu::impl::dataproc::opcode_and_LSL_Rm_0, // 0x008
        NULL, // 0x009
        gbaemu::gba::cpu::impl::dataproc::opcode_and_LSR_Rm_0, // 0x00a
        NULL, // 0x00b
        gbaemu::gba::cpu::impl::dataproc::opcode_and_ASR_Rm_0, // 0x00c
        NULL, // 0x00d
        gbaemu::gba::cpu::impl::dataproc::opcode_and_ROR_Rm_0, // 0x00e
        NULL, // 0x00f
        gbaemu::gba::cpu::impl::dataproc::opcode_ands_LSL_Rm_0, // 0x010
        gbaemu::gba::cpu::impl::dataproc::opcode_ands_LSL_Rm_1, // 0x011
        gbaemu::gba::cpu::impl::dataproc::opcode_ands_LSR_Rm_0, // 0x012
        gbaemu::gba::cpu::impl::dataproc::opcode_ands_LSR_Rm_1, // 0x013
        gbaemu::gba::cpu::impl::dataproc::opcode_ands_ASR_Rm_0, // 0x014
        gbaemu::gba::cpu::impl::dataproc::opcode_ands_ASR_Rm_1, // 0x015
        gbaemu::gba::cpu::impl::dataproc::opcode_ands_ROR_Rm_0, // 0x016
        gbaemu::gba::cpu::impl::dataproc::opcode_ands_ROR_Rm_1, // 0x017
        gbaemu::gba::cpu::impl::dataproc::opcode_ands_LSL_Rm_0, // 0x018
        NULL, // 0x019
        gbaemu::gba::cpu::impl::dataproc::opcode_ands_LSR_Rm_0, // 0x01a
        NULL, // 0x01b
        gbaemu::gba::cpu::impl::dataproc::opcode_ands_ASR_Rm_0, // 0x01c
        NULL, // 0x01d
        gbaemu::gba::cpu::impl::dataproc::opcode_ands_ROR_Rm_0, // 0x01e
        NULL, // 0x01f
        gbaemu::gba::cpu::impl::dataproc::opcode_eor_LSL_Rm_0, // 0x020
        gbaemu::gba::cpu::impl::dataproc::opcode_eor_LSL_Rm_1, // 0x021
        gbaemu::gba::cpu::impl::dataproc::opcode_eor_LSR_Rm_0, // 0x022
        gbaemu::gba::cpu::impl::dataproc::opcode_eor_LSR_Rm_1, // 0x023
        gbaemu::gba::cpu::impl::dataproc::opcode_eor_ASR_Rm_0, // 0x024
        gbaemu::gba::cpu::impl::dataproc::opcode_eor_ASR_Rm_1, // 0x025
        gbaemu::gba::cpu::impl::dataproc::opcode_eor_ROR_Rm_0, // 0x026
        gbaemu::gba::cpu::impl::dataproc::opcode_eor_ROR_Rm_1, // 0x027
        gbaemu::gba::cpu::impl::dataproc::opcode_eor_LSL_Rm_0, // 0x028
        NULL, // 0x029
        gbaemu::gba::cpu::impl::dataproc::opcode_eor_LSR_Rm_0, // 0x02a
        NULL, // 0x02b
        gbaemu::gba::cpu::impl::dataproc::opcode_eor_ASR_Rm_0, // 0x02c
        NULL, // 0x02d
        gbaemu::gba::cpu::impl::dataproc::opcode_eor_ROR_Rm_0, // 0x02e
        NULL, // 0x02f
        gbaemu::gba::cpu::impl::dataproc::opcode_eors_LSL_Rm_0, // 0x030
        gbaemu::gba::cpu::impl::dataproc::opcode_eors_LSL_Rm_1, // 0x031
        gbaemu::gba::cpu::impl::dataproc::opcode_eors_LSR_Rm_0, // 0x032
        gbaemu::gba::cpu::impl::dataproc::opcode_eors_LSR_Rm_1, // 0x033
        gbaemu::gba::cpu::impl::dataproc::opcode_eors_ASR_Rm_0, // 0x034
        gbaemu::gba::cpu::impl::dataproc::opcode_eors_ASR_Rm_1, // 0x035
        gbaemu::gba::cpu::impl::dataproc::opcode_eors_ROR_Rm_0, // 0x036
        gbaemu::gba::cpu::impl::dataproc::opcode_eors_ROR_Rm_1, // 0x037
        gbaemu::gba::cpu::impl::dataproc::opcode_eors_LSL_Rm_0, // 0x038
        NULL, // 0x039
        gbaemu::gba::cpu::impl::dataproc::opcode_eors_LSR_Rm_0, // 0x03a
        NULL, // 0x03b
        gbaemu::gba::cpu::impl::dataproc::opcode_eors_ASR_Rm_0, // 0x03c
        NULL, // 0x03d
        gbaemu::gba::cpu::impl::dataproc::opcode_eors_ROR_Rm_0, // 0x03e
        NULL, // 0x03f
        gbaemu::gba::cpu::impl::dataproc::opcode_sub_LSL_Rm_0, // 0x040
        gbaemu::gba::cpu::impl::dataproc::opcode_sub_LSL_Rm_1, // 0x041
        gbaemu::gba::cpu::impl::dataproc::opcode_sub_LSR_Rm_0, // 0x042
        gbaemu::gba::cpu::impl::dataproc::opcode_sub_LSR_Rm_1, // 0x043
        gbaemu::gba::cpu::impl::dataproc::opcode_sub_ASR_Rm_0, // 0x044
        gbaemu::gba::cpu::impl::dataproc::opcode_sub_ASR_Rm_1, // 0x045
        gbaemu::gba::cpu::impl::dataproc::opcode_sub_ROR_Rm_0, // 0x046
        gbaemu::gba::cpu::impl::dataproc::opcode_sub_ROR_Rm_1, // 0x047
        gbaemu::gba::cpu::impl::dataproc::opcode_sub_LSL_Rm_0, // 0x048
        NULL, // 0x049
        gbaemu::gba::cpu::impl::dataproc::opcode_sub_LSR_Rm_0, // 0x04a
        NULL, // 0x04b
        gbaemu::gba::cpu::impl::dataproc::opcode_sub_ASR_Rm_0, // 0x04c
        NULL, // 0x04d
        gbaemu::gba::cpu::impl::dataproc::opcode_sub_ROR_Rm_0, // 0x04e
        NULL, // 0x04f
        gbaemu::gba::cpu::impl::dataproc::opcode_subs_LSL_Rm_0, // 0x050
        gbaemu::gba::cpu::impl::dataproc::opcode_subs_LSL_Rm_1, // 0x051
        gbaemu::gba::cpu::impl::dataproc::opcode_subs_LSR_Rm_0, // 0x052
        gbaemu::gba::cpu::impl::dataproc::opcode_subs_LSR_Rm_1, // 0x053
        gbaemu::gba::cpu::impl::dataproc::opcode_subs_ASR_Rm_0, // 0x054
        gbaemu::gba::cpu::impl::dataproc::opcode_subs_ASR_Rm_1, // 0x055
        gbaemu::gba::cpu::impl::dataproc::opcode_subs_ROR_Rm_0, // 0x056
        gbaemu::gba::cpu::impl::dataproc::opcode_subs_ROR_Rm_1, // 0x057
        gbaemu::gba::cpu::impl::dataproc::opcode_subs_LSL_Rm_0, // 0x058
        NULL, // 0x059
        gbaemu::gba::cpu::impl::dataproc::opcode_subs_LSR_Rm_0, // 0x05a
        NULL, // 0x05b
        gbaemu::gba::cpu::impl::dataproc::opcode_subs_ASR_Rm_0, // 0x05c
        NULL, // 0x05d
        gbaemu::gba::cpu::impl::dataproc::opcode_subs_ROR_Rm_0, // 0x05e
        NULL, // 0x05f
        gbaemu::gba::cpu::impl::dataproc::opcode_rsb_LSL_Rm_0, // 0x060
        gbaemu::gba::cpu::impl::dataproc::opcode_rsb_LSL_Rm_1, // 0x061
        gbaemu::gba::cpu::impl::dataproc::opcode_rsb_LSR_Rm_0, // 0x062
        gbaemu::gba::cpu::impl::dataproc::opcode_rsb_LSR_Rm_1, // 0x063
        gbaemu::gba::cpu::impl::dataproc::opcode_rsb_ASR_Rm_0, // 0x064
        gbaemu::gba::cpu::impl::dataproc::opcode_rsb_ASR_Rm_1, // 0x065
        gbaemu::gba::cpu::impl::dataproc::opcode_rsb_ROR_Rm_0, // 0x066
        gbaemu::gba::cpu::impl::dataproc::opcode_rsb_ROR_Rm_1, // 0x067
        gbaemu::gba::cpu::impl::dataproc::opcode_rsb_LSL_Rm_0, // 0x068
        NULL, // 0x069
        gbaemu::gba::cpu::impl::dataproc::opcode_rsb_LSR_Rm_0, // 0x06a
        NULL, // 0x06b
        gbaemu::gba::cpu::impl::dataproc::opcode_rsb_ASR_Rm_0, // 0x06c
        NULL, // 0x06d
        gbaemu::gba::cpu::impl::dataproc::opcode_rsb_ROR_Rm_0, // 0x06e
        NULL, // 0x06f
        gbaemu::gba::cpu::impl::dataproc::opcode_rsbs_LSL_Rm_0, // 0x070
        gbaemu::gba::cpu::impl::dataproc::opcode_rsbs_LSL_Rm_1, // 0x071
        gbaemu::gba::cpu::impl::dataproc::opcode_rsbs_LSR_Rm_0, // 0x072
        gbaemu::gba::cpu::impl::dataproc::opcode_rsbs_LSR_Rm_1, // 0x073
        gbaemu::gba::cpu::impl::dataproc::opcode_rsbs_ASR_Rm_0, // 0x074
        gbaemu::gba::cpu::impl::dataproc::opcode_rsbs_ASR_Rm_1, // 0x075
        gbaemu::gba::cpu::impl::dataproc::opcode_rsbs_ROR_Rm_0, // 0x076
        gbaemu::gba::cpu::impl::dataproc::opcode_rsbs_ROR_Rm_1, // 0x077
        gbaemu::gba::cpu::impl::dataproc::opcode_rsbs_LSL_Rm_0, // 0x078
        NULL, // 0x079
        gbaemu::gba::cpu::impl::dataproc::opcode_rsbs_LSR_Rm_0, // 0x07a
        NULL, // 0x07b
        gbaemu::gba::cpu::impl::dataproc::opcode_rsbs_ASR_Rm_0, // 0x07c
        NULL, // 0x07d
        gbaemu::gba::cpu::impl::dataproc::opcode_rsbs_ROR_Rm_0, // 0x07e
        NULL, // 0x07f
        gbaemu::gba::cpu::impl::dataproc::opcode_add_LSL_Rm_0, // 0x080
        gbaemu::gba::cpu::impl::dataproc::opcode_add_LSL_Rm_1, // 0x081
        gbaemu::gba::cpu::impl::dataproc::opcode_add_LSR_Rm_0, // 0x082
        gbaemu::gba::cpu::impl::dataproc::opcode_add_LSR_Rm_1, // 0x083
        gbaemu::gba::cpu::impl::dataproc::opcode_add_ASR_Rm_0, // 0x084
        gbaemu::gba::cpu::impl::dataproc::opcode_add_ASR_Rm_1, // 0x085
        gbaemu::gba::cpu::impl::dataproc::opcode_add_ROR_Rm_0, // 0x086
        gbaemu::gba::cpu::impl::dataproc::opcode_add_ROR_Rm_1, // 0x087
        gbaemu::gba::cpu::impl::dataproc::opcode_add_LSL_Rm_0, // 0x088
        NULL, // 0x089
        gbaemu::gba::cpu::impl::dataproc::opcode_add_LSR_Rm_0, // 0x08a
        NULL, // 0x08b
        gbaemu::gba::cpu::impl::dataproc::opcode_add_ASR_Rm_0, // 0x08c
        NULL, // 0x08d
        gbaemu::gba::cpu::impl::dataproc::opcode_add_ROR_Rm_0, // 0x08e
        NULL, // 0x08f
        gbaemu::gba::cpu::impl::dataproc::opcode_adds_LSL_Rm_0, // 0x090
        gbaemu::gba::cpu::impl::dataproc::opcode_adds_LSL_Rm_1, // 0x091
        gbaemu::gba::cpu::impl::dataproc::opcode_adds_LSR_Rm_0, // 0x092
        gbaemu::gba::cpu::impl::dataproc::opcode_adds_LSR_Rm_1, // 0x093
        gbaemu::gba::cpu::impl::dataproc::opcode_adds_ASR_Rm_0, // 0x094
        gbaemu::gba::cpu::impl::dataproc::opcode_adds_ASR_Rm_1, // 0x095
        gbaemu::gba::cpu::impl::dataproc::opcode_adds_ROR_Rm_0, // 0x096
        gbaemu::gba::cpu::impl::dataproc::opcode_adds_ROR_Rm_1, // 0x097
        gbaemu::gba::cpu::impl::dataproc::opcode_adds_LSL_Rm_0, // 0x098
        NULL, // 0x099
        gbaemu::gba::cpu::impl::dataproc::opcode_adds_LSR_Rm_0, // 0x09a
        NULL, // 0x09b
        gbaemu::gba::cpu::impl::dataproc::opcode_adds_ASR_Rm_0, // 0x09c
        NULL, // 0x09d
        gbaemu::gba::cpu::impl::dataproc::opcode_adds_ROR_Rm_0, // 0x09e
        NULL, // 0x09f
        gbaemu::gba::cpu::impl::dataproc::opcode_adc_LSL_Rm_0, // 0x0a0
        gbaemu::gba::cpu::impl::dataproc::opcode_adc_LSL_Rm_1, // 0x0a1
        gbaemu::gba::cpu::impl::dataproc::opcode_adc_LSR_Rm_0, // 0x0a2
        gbaemu::gba::cpu::impl::dataproc::opcode_adc_LSR_Rm_1, // 0x0a3
        gbaemu::gba::cpu::impl::dataproc::opcode_adc_ASR_Rm_0, // 0x0a4
        gbaemu::gba::cpu::impl::dataproc::opcode_adc_ASR_Rm_1, // 0x0a5
        gbaemu::gba::cpu::impl::dataproc::opcode_adc_ROR_Rm_0, // 0x0a6
        gbaemu::gba::cpu::impl::dataproc::opcode_adc_ROR_Rm_1, // 0x0a7
        gbaemu::gba::cpu::impl::dataproc::opcode_adc_LSL_Rm_0, // 0x0a8
        NULL, // 0x0a9
        gbaemu::gba::cpu::impl::dataproc::opcode_adc_LSR_Rm_0, // 0x0aa
        NULL, // 0x0ab
        gbaemu::gba::cpu::impl::dataproc::opcode_adc_ASR_Rm_0, // 0x0ac
        NULL, // 0x0ad
        gbaemu::gba::cpu::impl::dataproc::opcode_adc_ROR_Rm_0, // 0x0ae
        NULL, // 0x0af
        gbaemu::gba::cpu::impl::dataproc::opcode_adcs_LSL_Rm_0, // 0x0b0
        gbaemu::gba::cpu::impl::dataproc::opcode_adcs_LSL_Rm_1, // 0x0b1
        gbaemu::gba::cpu::impl::dataproc::opcode_adcs_LSR_Rm_0, // 0x0b2
        gbaemu::gba::cpu::impl::dataproc::opcode_adcs_LSR_Rm_1, // 0x0b3
        gbaemu::gba::cpu::impl::dataproc::opcode_adcs_ASR_Rm_0, // 0x0b4
        gbaemu::gba::cpu::impl::dataproc::opcode_adcs_ASR_Rm_1, // 0x0b5
        gbaemu::gba::cpu::impl::dataproc::opcode_adcs_ROR_Rm_0, // 0x0b6
        gbaemu::gba::cpu::impl::dataproc::opcode_adcs_ROR_Rm_1, // 0x0b7
        gbaemu::gba::cpu::impl::dataproc::opcode_adcs_LSL_Rm_0, // 0x0b8
        NULL, // 0x0b9
        gbaemu::gba::cpu::impl::dataproc::opcode_adcs_LSR_Rm_0, // 0x0ba
        NULL, // 0x0bb
        gbaemu::gba::cpu::impl::dataproc::opcode_adcs_ASR_Rm_0, // 0x0bc
        NULL, // 0x0bd
        gbaemu::gba::cpu::impl::dataproc::opcode_adcs_ROR_Rm_0, // 0x0be
        NULL, // 0x0bf
        gbaemu::gba::cpu::impl::dataproc::opcode_sbc_LSL_Rm_0, // 0x0c0
        gbaemu::gba::cpu::impl::dataproc::opcode_sbc_LSL_Rm_1, // 0x0c1
        gbaemu::gba::cpu::impl::dataproc::opcode_sbc_LSR_Rm_0, // 0x0c2
        gbaemu::gba::cpu::impl::dataproc::opcode_sbc_LSR_Rm_1, // 0x0c3
        gbaemu::gba::cpu::impl::dataproc::opcode_sbc_ASR_Rm_0, // 0x0c4
        gbaemu::gba::cpu::impl::dataproc::opcode_sbc_ASR_Rm_1, // 0x0c5
        gbaemu::gba::cpu::impl::dataproc::opcode_sbc_ROR_Rm_0, // 0x0c6
        gbaemu::gba::cpu::impl::dataproc::opcode_sbc_ROR_Rm_1, // 0x0c7
        gbaemu::gba::cpu::impl::dataproc::opcode_sbc_LSL_Rm_0, // 0x0c8
        NULL, // 0x0c9
        gbaemu::gba::cpu::impl::dataproc::opcode_sbc_LSR_Rm_0, // 0x0ca
        NULL, // 0x0cb
        gbaemu::gba::cpu::impl::dataproc::opcode_sbc_ASR_Rm_0, // 0x0cc
        NULL, // 0x0cd
        gbaemu::gba::cpu::impl::dataproc::opcode_sbc_ROR_Rm_0, // 0x0ce
        NULL, // 0x0cf
        gbaemu::gba::cpu::impl::dataproc::opcode_sbcs_LSL_Rm_0, // 0x0d0
        gbaemu::gba::cpu::impl::dataproc::opcode_sbcs_LSL_Rm_1, // 0x0d1
        gbaemu::gba::cpu::impl::dataproc::opcode_sbcs_LSR_Rm_0, // 0x0d2
        gbaemu::gba::cpu::impl::dataproc::opcode_sbcs_LSR_Rm_1, // 0x0d3
        gbaemu::gba::cpu::impl::dataproc::opcode_sbcs_ASR_Rm_0, // 0x0d4
        gbaemu::gba::cpu::impl::dataproc::opcode_sbcs_ASR_Rm_1, // 0x0d5
        gbaemu::gba::cpu::impl::dataproc::opcode_sbcs_ROR_Rm_0, // 0x0d6
        gbaemu::gba::cpu::impl::dataproc::opcode_sbcs_ROR_Rm_1, // 0x0d7
        gbaemu::gba::cpu::impl::dataproc::opcode_sbcs_LSL_Rm_0, // 0x0d8
        NULL, // 0x0d9
        gbaemu::gba::cpu::impl::dataproc::opcode_sbcs_LSR_Rm_0, // 0x0da
        NULL, // 0x0db
        gbaemu::gba::cpu::impl::dataproc::opcode_sbcs_ASR_Rm_0, // 0x0dc
        NULL, // 0x0dd
        gbaemu::gba::cpu::impl::dataproc::opcode_sbcs_ROR_Rm_0, // 0x0de
        NULL, // 0x0df
        gbaemu::gba::cpu::impl::dataproc::opcode_rsc_LSL_Rm_0, // 0x0e0
        gbaemu::gba::cpu::impl::dataproc::opcode_rsc_LSL_Rm_1, // 0x0e1
        gbaemu::gba::cpu::impl::dataproc::opcode_rsc_LSR_Rm_0, // 0x0e2
        gbaemu::gba::cpu::impl::dataproc::opcode_rsc_LSR_Rm_1, // 0x0e3
        gbaemu::gba::cpu::impl::dataproc::opcode_rsc_ASR_Rm_0, // 0x0e4
        gbaemu::gba::cpu::impl::dataproc::opcode_rsc_ASR_Rm_1, // 0x0e5
        gbaemu::gba::cpu::impl::dataproc::opcode_rsc_ROR_Rm_0, // 0x0e6
        gbaemu::gba::cpu::impl::dataproc::opcode_rsc_ROR_Rm_1, // 0x0e7
        gbaemu::gba::cpu::impl::dataproc::opcode_rsc_LSL_Rm_0, // 0x0e8
        NULL, // 0x0e9
        gbaemu::gba::cpu::impl::dataproc::opcode_rsc_LSR_Rm_0, // 0x0ea
        NULL, // 0x0eb
        gbaemu::gba::cpu::impl::dataproc::opcode_rsc_ASR_Rm_0, // 0x0ec
        NULL, // 0x0ed
        gbaemu::gba::cpu::impl::dataproc::opcode_rsc_ROR_Rm_0, // 0x0ee
        NULL, // 0x0ef
        gbaemu::gba::cpu::impl::dataproc::opcode_rscs_LSL_Rm_0, // 0x0f0
        gbaemu::gba::cpu::impl::dataproc::opcode_rscs_LSL_Rm_1, // 0x0f1
        gbaemu::gba::cpu::impl::dataproc::opcode_rscs_LSR_Rm_0, // 0x0f2
        gbaemu::gba::cpu::impl::dataproc::opcode_rscs_LSR_Rm_1, // 0x0f3
        gbaemu::gba::cpu::impl::dataproc::opcode_rscs_ASR_Rm_0, // 0x0f4
        gbaemu::gba::cpu::impl::dataproc::opcode_rscs_ASR_Rm_1, // 0x0f5
        gbaemu::gba::cpu::impl::dataproc::opcode_rscs_ROR_Rm_0, // 0x0f6
        gbaemu::gba::cpu::impl::dataproc::opcode_rscs_ROR_Rm_1, // 0x0f7
        gbaemu::gba::cpu::impl::dataproc::opcode_rscs_LSL_Rm_0, // 0x0f8
        NULL, // 0x0f9
        gbaemu::gba::cpu::impl::dataproc::opcode_rscs_LSR_Rm_0, // 0x0fa
        NULL, // 0x0fb
        gbaemu::gba::cpu::impl::dataproc::opcode_rscs_ASR_Rm_0, // 0x0fc
        NULL, // 0x0fd
        gbaemu::gba::cpu::impl::dataproc::opcode_rscs_ROR_Rm_0, // 0x0fe
        NULL, // 0x0ff
        NULL, // 0x100
        NULL, // 0x101
        NULL, // 0x102
        NULL, // 0x103
        NULL, // 0x104
        NULL, // 0x105
        NULL, // 0x106
        NULL, // 0x107
        NULL, // 0x108
        NULL, // 0x109
        NULL, // 0x10a
        NULL, // 0x10b
        NULL, // 0x10c
        NULL, // 0x10d
        NULL, // 0x10e
        NULL, // 0x10f
        gbaemu::gba::cpu::impl::dataproc::opcode_tst_LSL_Rm_0, // 0x110
        gbaemu::gba::cpu::impl::dataproc::opcode_tst_LSL_Rm_1, // 0x111
        gbaemu::gba::cpu::impl::dataproc::opcode_tst_LSR_Rm_0, // 0x112
        gbaemu::gba::cpu::impl::dataproc::opcode_tst_LSR_Rm_1, // 0x113
        gbaemu::gba::cpu::impl::dataproc::opcode_tst_ASR_Rm_0, // 0x114
        gbaemu::gba::cpu::impl::dataproc::opcode_tst_ASR_Rm_1, // 0x115
        gbaemu::gba::cpu::impl::dataproc::opcode_tst_ROR_Rm_0, // 0x116
        gbaemu::gba::cpu::impl::dataproc::opcode_tst_ROR_Rm_1, // 0x117
        gbaemu::gba::cpu::impl::dataproc::opcode_tst_LSL_Rm_0, // 0x118
        NULL, // 0x119
        gbaemu::gba::cpu::impl::dataproc::opcode_tst_LSR_Rm_0, // 0x11a
        NULL, // 0x11b
        gbaemu::gba::cpu::impl::dataproc::opcode_tst_ASR_Rm_0, // 0x11c
        NULL, // 0x11d
        gbaemu::gba::cpu::impl::dataproc::opcode_tst_ROR_Rm_0, // 0x11e
        NULL, // 0x11f
        NULL, // 0x120
        gbaemu::gba::cpu::impl::branch::bx, // 0x121
        NULL, // 0x122
        NULL, // 0x123
        NULL, // 0x124
        NULL, // 0x125
        NULL, // 0x126
        NULL, // 0x127
        NULL, // 0x128
        NULL, // 0x129
        NULL, // 0x12a
        NULL, // 0x12b
        NULL, // 0x12c
        NULL, // 0x12d
        NULL, // 0x12e
        NULL, // 0x12f
        gbaemu::gba::cpu::impl::dataproc::opcode_teq_LSL_Rm_0, // 0x130
        gbaemu::gba::cpu::impl::dataproc::opcode_teq_LSL_Rm_1, // 0x131
        gbaemu::gba::cpu::impl::dataproc::opcode_teq_LSR_Rm_0, // 0x132
        gbaemu::gba::cpu::impl::dataproc::opcode_teq_LSR_Rm_0, // 0x133
        gbaemu::gba::cpu::impl::dataproc::opcode_teq_ASR_Rm_0, // 0x134
        gbaemu::gba::cpu::impl::dataproc::opcode_teq_ASR_Rm_1, // 0x135
        gbaemu::gba::cpu::impl::dataproc::opcode_teq_ROR_Rm_0, // 0x136
        gbaemu::gba::cpu::impl::dataproc::opcode_teq_ROR_Rm_1, // 0x137
        gbaemu::gba::cpu::impl::dataproc::opcode_teq_LSL_Rm_0, // 0x138
        NULL, // 0x139
        gbaemu::gba::cpu::impl::dataproc::opcode_teq_LSR_Rm_0, // 0x13a
        NULL, // 0x13b
        gbaemu::gba::cpu::impl::dataproc::opcode_teq_ASR_Rm_0, // 0x13c
        NULL, // 0x13d
        gbaemu::gba::cpu::impl::dataproc::opcode_teq_ROR_Rm_0, // 0x13e
        NULL, // 0x13f
        NULL, // 0x140
        NULL, // 0x141
        NULL, // 0x142
        NULL, // 0x143
        NULL, // 0x144
        NULL, // 0x145
        NULL, // 0x146
        NULL, // 0x147
        NULL, // 0x148
        NULL, // 0x149
        NULL, // 0x14a
        NULL, // 0x14b
        NULL, // 0x14c
        NULL, // 0x14d
        NULL, // 0x14e
        NULL, // 0x14f
        gbaemu::gba::cpu::impl::dataproc::opcode_cmp_LSL_Rm_0, // 0x150
        gbaemu::gba::cpu::impl::dataproc::opcode_cmp_LSL_Rm_1, // 0x151
        gbaemu::gba::cpu::impl::dataproc::opcode_cmp_LSR_Rm_0, // 0x152
        gbaemu::gba::cpu::impl::dataproc::opcode_cmp_LSR_Rm_1, // 0x153
        gbaemu::gba::cpu::impl::dataproc::opcode_cmp_ASR_Rm_0, // 0x154
        gbaemu::gba::cpu::impl::dataproc::opcode_cmp_ASR_Rm_1, // 0x155
        gbaemu::gba::cpu::impl::dataproc::opcode_cmp_ROR_Rm_0, // 0x156
        gbaemu::gba::cpu::impl::dataproc::opcode_cmp_ROR_Rm_1, // 0x157
        gbaemu::gba::cpu::impl::dataproc::opcode_cmp_LSL_Rm_0, // 0x158
        NULL, // 0x159
        gbaemu::gba::cpu::impl::dataproc::opcode_cmp_LSR_Rm_0, // 0x15a
        NULL, // 0x15b
        gbaemu::gba::cpu::impl::dataproc::opcode_cmp_ASR_Rm_0, // 0x15c
        NULL, // 0x15d
        gbaemu::gba::cpu::impl::dataproc::opcode_cmp_ROR_Rm_0, // 0x15e
        NULL, // 0x15f
        NULL, // 0x160
        NULL, // 0x161
        NULL, // 0x162
        NULL, // 0x163
        NULL, // 0x164
        NULL, // 0x165
        NULL, // 0x166
        NULL, // 0x167
        NULL, // 0x168
        NULL, // 0x169
        NULL, // 0x16a
        NULL, // 0x16b
        NULL, // 0x16c
        NULL, // 0x16d
        NULL, // 0x16e
        NULL, // 0x16f
        gbaemu::gba::cpu::impl::dataproc::opcode_cmn_LSL_Rm_0, // 0x170
        gbaemu::gba::cpu::impl::dataproc::opcode_cmn_LSL_Rm_1, // 0x171
        gbaemu::gba::cpu::impl::dataproc::opcode_cmn_LSR_Rm_0, // 0x172
        gbaemu::gba::cpu::impl::dataproc::opcode_cmn_LSR_Rm_1, // 0x173
        gbaemu::gba::cpu::impl::dataproc::opcode_cmn_ASR_Rm_0, // 0x174
        gbaemu::gba::cpu::impl::dataproc::opcode_cmn_ASR_Rm_1, // 0x175
        gbaemu::gba::cpu::impl::dataproc::opcode_cmn_ROR_Rm_0, // 0x176
        gbaemu::gba::cpu::impl::dataproc::opcode_cmn_ROR_Rm_1, // 0x177
        gbaemu::gba::cpu::impl::dataproc::opcode_cmn_LSL_Rm_0, // 0x178
        NULL, // 0x179
        gbaemu::gba::cpu::impl::dataproc::opcode_cmn_LSR_Rm_0, // 0x17a
        NULL, // 0x17b
        gbaemu::gba::cpu::impl::dataproc::opcode_cmn_ASR_Rm_0, // 0x17c
        NULL, // 0x17d
        gbaemu::gba::cpu::impl::dataproc::opcode_cmn_ROR_Rm_0, // 0x17e
        NULL, // 0x17f
        gbaemu::gba::cpu::impl::dataproc::opcode_orr_LSL_Rm_0, // 0x180
        gbaemu::gba::cpu::impl::dataproc::opcode_orr_LSL_Rm_1, // 0x181
        gbaemu::gba::cpu::impl::dataproc::opcode_orr_LSR_Rm_0, // 0x182
        gbaemu::gba::cpu::impl::dataproc::opcode_orr_LSR_Rm_1, // 0x183
        gbaemu::gba::cpu::impl::dataproc::opcode_orr_ASR_Rm_0, // 0x184
        gbaemu::gba::cpu::impl::dataproc::opcode_orr_ASR_Rm_1, // 0x185
        gbaemu::gba::cpu::impl::dataproc::opcode_orr_ROR_Rm_0, // 0x186
        gbaemu::gba::cpu::impl::dataproc::opcode_orr_ROR_Rm_1, // 0x187
        gbaemu::gba::cpu::impl::dataproc::opcode_orr_LSL_Rm_0, // 0x188
        NULL, // 0x189
        gbaemu::gba::cpu::impl::dataproc::opcode_orr_LSR_Rm_0, // 0x18a
        NULL, // 0x18b
        gbaemu::gba::cpu::impl::dataproc::opcode_orr_ASR_Rm_0, // 0x18c
        NULL, // 0x18d
        gbaemu::gba::cpu::impl::dataproc::opcode_orr_ROR_Rm_0, // 0x18e
        NULL, // 0x18f
        gbaemu::gba::cpu::impl::dataproc::opcode_orrs_LSL_Rm_0, // 0x190
        gbaemu::gba::cpu::impl::dataproc::opcode_orrs_LSL_Rm_1, // 0x191
        gbaemu::gba::cpu::impl::dataproc::opcode_orrs_LSR_Rm_0, // 0x192
        gbaemu::gba::cpu::impl::dataproc::opcode_orrs_LSR_Rm_1, // 0x193
        gbaemu::gba::cpu::impl::dataproc::opcode_orrs_ASR_Rm_0, // 0x194
        gbaemu::gba::cpu::impl::dataproc::opcode_orrs_ASR_Rm_1, // 0x195
        gbaemu::gba::cpu::impl::dataproc::opcode_orrs_ROR_Rm_0, // 0x196
        gbaemu::gba::cpu::impl::dataproc::opcode_orrs_ROR_Rm_1, // 0x197
        gbaemu::gba::cpu::impl::dataproc::opcode_orrs_LSL_Rm_0, // 0x198
        NULL, // 0x199
        gbaemu::gba::cpu::impl::dataproc::opcode_orrs_LSR_Rm_0, // 0x19a
        NULL, // 0x19b
        gbaemu::gba::cpu::impl::dataproc::opcode_orrs_ASR_Rm_0, // 0x19c
        NULL, // 0x19d
        gbaemu::gba::cpu::impl::dataproc::opcode_orrs_ROR_Rm_0, // 0x19e
        NULL, // 0x19f
        gbaemu::gba::cpu::impl::dataproc::opcode_mov_LSL_Rm_0, // 0x1a0
        gbaemu::gba::cpu::impl::dataproc::opcode_mov_LSL_Rm_1, // 0x1a1
        gbaemu::gba::cpu::impl::dataproc::opcode_mov_LSR_Rm_0, // 0x1a2
        gbaemu::gba::cpu::impl::dataproc::opcode_mov_LSR_Rm_1, // 0x1a3
        gbaemu::gba::cpu::impl::dataproc::opcode_mov_ASR_Rm_0, // 0x1a4
        gbaemu::gba::cpu::impl::dataproc::opcode_mov_ASR_Rm_1, // 0x1a5
        gbaemu::gba::cpu::impl::dataproc::opcode_mov_ROR_Rm_0, // 0x1a6
        gbaemu::gba::cpu::impl::dataproc::opcode_mov_ROR_Rm_1, // 0x1a7
        gbaemu::gba::cpu::impl::dataproc::opcode_mov_LSL_Rm_0, // 0x1a8
        NULL, // 0x1a9
        gbaemu::gba::cpu::impl::dataproc::opcode_mov_LSR_Rm_0, // 0x1aa
        NULL, // 0x1ab
        gbaemu::gba::cpu::impl::dataproc::opcode_mov_ASR_Rm_0, // 0x1ac
        NULL, // 0x1ad
        gbaemu::gba::cpu::impl::dataproc::opcode_mov_ROR_Rm_0, // 0x1ae
        NULL, // 0x1af
        gbaemu::gba::cpu::impl::dataproc::opcode_movs_LSL_Rm_0, // 0x1b0
        gbaemu::gba::cpu::impl::dataproc::opcode_movs_LSL_Rm_1, // 0x1b1
        gbaemu::gba::cpu::impl::dataproc::opcode_movs_LSR_Rm_0, // 0x1b2
        gbaemu::gba::cpu::impl::dataproc::opcode_movs_LSR_Rm_1, // 0x1b3
        gbaemu::gba::cpu::impl::dataproc::opcode_movs_ASR_Rm_0, // 0x1b4
        gbaemu::gba::cpu::impl::dataproc::opcode_movs_ASR_Rm_1, // 0x1b5
        gbaemu::gba::cpu::impl::dataproc::opcode_movs_ROR_Rm_0, // 0x1b6
        gbaemu::gba::cpu::impl::dataproc::opcode_movs_ROR_Rm_1, // 0x1b7
        gbaemu::gba::cpu::impl::dataproc::opcode_movs_LSL_Rm_0, // 0x1b8
        NULL, // 0x1b9
        gbaemu::gba::cpu::impl::dataproc::opcode_movs_LSR_Rm_0, // 0x1ba
        NULL, // 0x1bb
        gbaemu::gba::cpu::impl::dataproc::opcode_movs_ASR_Rm_0, // 0x1bc
        NULL, // 0x1bd
        gbaemu::gba::cpu::impl::dataproc::opcode_movs_ROR_Rm_0, // 0x1be
        NULL, // 0x1bf
        gbaemu::gba::cpu::impl::dataproc::opcode_bic_LSL_Rm_0, // 0x1c0
        gbaemu::gba::cpu::impl::dataproc::opcode_bic_LSL_Rm_1, // 0x1c1
        gbaemu::gba::cpu::impl::dataproc::opcode_bic_LSR_Rm_0, // 0x1c2
        gbaemu::gba::cpu::impl::dataproc::opcode_bic_LSR_Rm_1, // 0x1c3
        gbaemu::gba::cpu::impl::dataproc::opcode_bic_ASR_Rm_0, // 0x1c4
        gbaemu::gba::cpu::impl::dataproc::opcode_bic_ASR_Rm_1, // 0x1c5
        gbaemu::gba::cpu::impl::dataproc::opcode_bic_ROR_Rm_0, // 0x1c6
        gbaemu::gba::cpu::impl::dataproc::opcode_bic_ROR_Rm_1, // 0x1c7
        gbaemu::gba::cpu::impl::dataproc::opcode_bic_LSL_Rm_0, // 0x1c8
        NULL, // 0x1c9
        gbaemu::gba::cpu::impl::dataproc::opcode_bic_LSR_Rm_0, // 0x1ca
        NULL, // 0x1cb
        gbaemu::gba::cpu::impl::dataproc::opcode_bic_ASR_Rm_0, // 0x1cc
        NULL, // 0x1cd
        gbaemu::gba::cpu::impl::dataproc::opcode_bic_ROR_Rm_0, // 0x1ce
        NULL, // 0x1cf
        gbaemu::gba::cpu::impl::dataproc::opcode_bics_LSL_Rm_0, // 0x1d0
        gbaemu::gba::cpu::impl::dataproc::opcode_bics_LSL_Rm_1, // 0x1d1
        gbaemu::gba::cpu::impl::dataproc::opcode_bics_LSR_Rm_0, // 0x1d2
        gbaemu::gba::cpu::impl::dataproc::opcode_bics_LSR_Rm_1, // 0x1d3
        gbaemu::gba::cpu::impl::dataproc::opcode_bics_ASR_Rm_0, // 0x1d4
        gbaemu::gba::cpu::impl::dataproc::opcode_bics_ASR_Rm_1, // 0x1d5
        gbaemu::gba::cpu::impl::dataproc::opcode_bics_ROR_Rm_0, // 0x1d6
        gbaemu::gba::cpu::impl::dataproc::opcode_bics_ROR_Rm_1, // 0x1d7
        gbaemu::gba::cpu::impl::dataproc::opcode_bics_LSL_Rm_0, // 0x1d8
        NULL, // 0x1d9
        gbaemu::gba::cpu::impl::dataproc::opcode_bics_LSR_Rm_0, // 0x1da
        NULL, // 0x1db
        gbaemu::gba::cpu::impl::dataproc::opcode_bics_ASR_Rm_0, // 0x1dc
        NULL, // 0x1dd
        gbaemu::gba::cpu::impl::dataproc::opcode_bics_ROR_Rm_0, // 0x1de
        NULL, // 0x1df
        gbaemu::gba::cpu::impl::dataproc::opcode_mvn_LSL_Rm_0, // 0x1e0
        gbaemu::gba::cpu::impl::dataproc::opcode_mvn_LSL_Rm_1, // 0x1e1
        gbaemu::gba::cpu::impl::dataproc::opcode_mvn_LSR_Rm_0, // 0x1e2
        gbaemu::gba::cpu::impl::dataproc::opcode_mvn_LSR_Rm_1, // 0x1e3
        gbaemu::gba::cpu::impl::dataproc::opcode_mvn_ASR_Rm_0, // 0x1e4
        gbaemu::gba::cpu::impl::dataproc::opcode_mvn_ASR_Rm_1, // 0x1e5
        gbaemu::gba::cpu::impl::dataproc::opcode_mvn_ROR_Rm_0, // 0x1e6
        gbaemu::gba::cpu::impl::dataproc::opcode_mvn_ROR_Rm_1, // 0x1e7
        gbaemu::gba::cpu::impl::dataproc::opcode_mvn_LSL_Rm_0, // 0x1e8
        NULL, // 0x1e9
        gbaemu::gba::cpu::impl::dataproc::opcode_mvn_LSR_Rm_0, // 0x1ea
        NULL, // 0x1eb
        gbaemu::gba::cpu::impl::dataproc::opcode_mvn_ASR_Rm_0, // 0x1ec
        NULL, // 0x1ed
        gbaemu::gba::cpu::impl::dataproc::opcode_mvn_ROR_Rm_0, // 0x1ee
        NULL, // 0x1ef
        gbaemu::gba::cpu::impl::dataproc::opcode_mvns_LSL_Rm_0, // 0x1f0
        gbaemu::gba::cpu::impl::dataproc::opcode_mvns_LSL_Rm_1, // 0x1f1
        gbaemu::gba::cpu::impl::dataproc::opcode_mvns_LSR_Rm_0, // 0x1f2
        gbaemu::gba::cpu::impl::dataproc::opcode_mvns_LSR_Rm_1, // 0x1f3
        gbaemu::gba::cpu::impl::dataproc::opcode_mvns_ASR_Rm_0, // 0x1f4
        gbaemu::gba::cpu::impl::dataproc::opcode_mvns_ASR_Rm_1, // 0x1f5
        gbaemu::gba::cpu::impl::dataproc::opcode_mvns_ROR_Rm_0, // 0x1f6
        gbaemu::gba::cpu::impl::dataproc::opcode_mvns_ROR_Rm_1, // 0x1f7
        gbaemu::gba::cpu::impl::dataproc::opcode_mvns_LSL_Rm_0, // 0x1f8
        NULL, // 0x1f9
        gbaemu::gba::cpu::impl::dataproc::opcode_mvns_LSR_Rm_0, // 0x1fa
        NULL, // 0x1fb
        gbaemu::gba::cpu::impl::dataproc::opcode_mvns_ASR_Rm_0, // 0x1fc
        NULL, // 0x1fd
        gbaemu::gba::cpu::impl::dataproc::opcode_mvns_ROR_Rm_0, // 0x1fe
        NULL, // 0x1ff
        REP16(gbaemu::gba::cpu::impl::dataproc::opcode_and_Immediate), // 0x200
        REP16(gbaemu::gba::cpu::impl::dataproc::opcode_ands_Immediate), // 0x210
        REP16(gbaemu::gba::cpu::impl::dataproc::opcode_eor_Immediate), // 0x220
        REP16(gbaemu::gba::cpu::impl::dataproc::opcode_eors_Immediate), // 0x230
        REP16(gbaemu::gba::cpu::impl::dataproc::opcode_sub_Immediate), // 0x240
        REP16(gbaemu::gba::cpu::impl::dataproc::opcode_subs_Immediate), // 0x250
        REP16(gbaemu::gba::cpu::impl::dataproc::opcode_rsb_Immediate), // 0x260
        REP16(gbaemu::gba::cpu::impl::dataproc::opcode_rsbs_Immediate), // 0x270
        REP16(gbaemu::gba::cpu::impl::dataproc::opcode_add_Immediate), // 0x280
        REP16(gbaemu::gba::cpu::impl::dataproc::opcode_adds_Immediate), // 0x290
        REP16(gbaemu::gba::cpu::impl::dataproc::opcode_adc_Immediate), // 0x2a0
        REP16(gbaemu::gba::cpu::impl::dataproc::opcode_adcs_Immediate), // 0x2b0
        REP16(gbaemu::gba::cpu::impl::dataproc::opcode_sbc_Immediate), // 0x2c0
        REP16(gbaemu::gba::cpu::impl::dataproc::opcode_sbcs_Immediate), // 0x2d0
        REP16(gbaemu::gba::cpu::impl::dataproc::opcode_rsc_Immediate), // 0x2e0
        REP16(gbaemu::gba::cpu::impl::dataproc::opcode_rscs_Immediate), // 0x2f0
        NULL, // 0x300
        NULL, // 0x301
        NULL, // 0x302
        NULL, // 0x303
        NULL, // 0x304
        NULL, // 0x305
        NULL, // 0x306
        NULL, // 0x307
        NULL, // 0x308
        NULL, // 0x309
        NULL, // 0x30a
        NULL, // 0x30b
        NULL, // 0x30c
        NULL, // 0x30d
        NULL, // 0x30e
        NULL, // 0x30f
        REP16(gbaemu::gba::cpu::impl::dataproc::opcode_tst_Immediate), // 0x310
        NULL, // 0x320
        NULL, // 0x321
        NULL, // 0x322
        NULL, // 0x323
        NULL, // 0x324
        NULL, // 0x325
        NULL, // 0x326
        NULL, // 0x327
        NULL, // 0x328
        NULL, // 0x329
        NULL, // 0x32a
        NULL, // 0x32b
        NULL, // 0x32c
        NULL, // 0x32d
        NULL, // 0x32e
        NULL, // 0x32f
        REP16(gbaemu::gba::cpu::impl::dataproc::opcode_teq_Immediate), // 0x330
        NULL, // 0x340
        NULL, // 0x341
        NULL, // 0x342
        NULL, // 0x343
        NULL, // 0x344
        NULL, // 0x345
        NULL, // 0x346
        NULL, // 0x347
        NULL, // 0x348
        NULL, // 0x349
        NULL, // 0x34a
        NULL, // 0x34b
        NULL, // 0x34c
        NULL, // 0x34d
        NULL, // 0x34e
        NULL, // 0x34f
        REP16(gbaemu::gba::cpu::impl::dataproc::opcode_cmp_Immediate), // 0x350
        NULL, // 0x360
        NULL, // 0x361
        NULL, // 0x362
        NULL, // 0x363
        NULL, // 0x364
        NULL, // 0x365
        NULL, // 0x366
        NULL, // 0x367
        NULL, // 0x368
        NULL, // 0x369
        NULL, // 0x36a
        NULL, // 0x36b
        NULL, // 0x36c
        NULL, // 0x36d
        NULL, // 0x36e
        NULL, // 0x36f
        REP16(gbaemu::gba::cpu::impl::dataproc::opcode_cmn_Immediate), // 0x370
        REP16(gbaemu::gba::cpu::impl::dataproc::opcode_orr_Immediate), // 0x380
        REP16(gbaemu::gba::cpu::impl::dataproc::opcode_orrs_Immediate), // 0x390
        REP16(gbaemu::gba::cpu::impl::dataproc::opcode_mov_Immediate), // 0x3a0
        REP16(gbaemu::gba::cpu::impl::dataproc::opcode_movs_Immediate), // 0x3b0
        REP16(gbaemu::gba::cpu::impl::dataproc::opcode_bic_Immediate), // 0x3c0
        REP16(gbaemu::gba::cpu::impl::dataproc::opcode_bics_Immediate), // 0x3d0
        REP16(gbaemu::gba::cpu::impl::dataproc::opcode_mvn_Immediate), // 0x3e0
        REP16(gbaemu::gba::cpu::impl::dataproc::opcode_mvns_Immediate), // 0x3f0
        gbaemu::gba::cpu::impl::sdt::opcode_str_LSL_Rm_0, // 0x400
        gbaemu::gba::cpu::impl::sdt::opcode_str_LSL_Rm_1, // 0x401
        gbaemu::gba::cpu::impl::sdt::opcode_str_LSR_Rm_0, // 0x402
        gbaemu::gba::cpu::impl::sdt::opcode_str_LSR_Rm_1, // 0x403
        gbaemu::gba::cpu::impl::sdt::opcode_str_ASR_Rm_0, // 0x404
        gbaemu::gba::cpu::impl::sdt::opcode_str_ASR_Rm_1, // 0x405
        gbaemu::gba::cpu::impl::sdt::opcode_str_ROR_Rm_0, // 0x406
        gbaemu::gba::cpu::impl::sdt::opcode_str_ROR_Rm_1, // 0x407
        gbaemu::gba::cpu::impl::sdt::opcode_str_LSL_Rm_0, // 0x408
        NULL, // 0x409
        gbaemu::gba::cpu::impl::sdt::opcode_str_LSR_Rm_0, // 0x40a
        NULL, // 0x40b
        gbaemu::gba::cpu::impl::sdt::opcode_str_ASR_Rm_0, // 0x40c
        NULL, // 0x40d
        gbaemu::gba::cpu::impl::sdt::opcode_str_ROR_Rm_0, // 0x40e
        NULL, // 0x40f
        gbaemu::gba::cpu::impl::sdt::opcode_ldr_LSL_Rm_0, // 0x410
        gbaemu::gba::cpu::impl::sdt::opcode_ldr_LSL_Rm_1, // 0x411
        gbaemu::gba::cpu::impl::sdt::opcode_ldr_LSR_Rm_0, // 0x412
        gbaemu::gba::cpu::impl::sdt::opcode_ldr_LSR_Rm_1, // 0x413
        gbaemu::gba::cpu::impl::sdt::opcode_ldr_ASR_Rm_0, // 0x414
        gbaemu::gba::cpu::impl::sdt::opcode_ldr_ASR_Rm_1, // 0x415
        gbaemu::gba::cpu::impl::sdt::opcode_ldr_ROR_Rm_0, // 0x416
        gbaemu::gba::cpu::impl::sdt::opcode_ldr_ROR_Rm_1, // 0x417
        gbaemu::gba::cpu::impl::sdt::opcode_ldr_LSL_Rm_0, // 0x418
        NULL, // 0x419
        gbaemu::gba::cpu::impl::sdt::opcode_ldr_LSR_Rm_0, // 0x41a
        NULL, // 0x41b
        gbaemu::gba::cpu::impl::sdt::opcode_ldr_ASR_Rm_0, // 0x41c
        NULL, // 0x41d
        gbaemu::gba::cpu::impl::sdt::opcode_ldr_ROR_Rm_0, // 0x41e
        NULL, // 0x41f
        NULL, // 0x420
        NULL, // 0x421
        NULL, // 0x422
        NULL, // 0x423
        NULL, // 0x424
        NULL, // 0x425
        NULL, // 0x426
        NULL, // 0x427
        NULL, // 0x428
        NULL, // 0x429
        NULL, // 0x42a
        NULL, // 0x42b
        NULL, // 0x42c
        NULL, // 0x42d
        NULL, // 0x42e
        NULL, // 0x42f
        NULL, // 0x430
        NULL, // 0x431
        NULL, // 0x432
        NULL, // 0x433
        NULL, // 0x434
        NULL, // 0x435
        NULL, // 0x436
        NULL, // 0x437
        NULL, // 0x438
        NULL, // 0x439
        NULL, // 0x43a
        NULL, // 0x43b
        NULL, // 0x43c
        NULL, // 0x43d
        NULL, // 0x43e
        NULL, // 0x43f
        gbaemu::gba::cpu::impl::sdt::opcode_strb_LSL_Rm_0, // 0x440
        gbaemu::gba::cpu::impl::sdt::opcode_strb_LSL_Rm_1, // 0x441
        gbaemu::gba::cpu::impl::sdt::opcode_strb_LSR_Rm_0, // 0x442
        gbaemu::gba::cpu::impl::sdt::opcode_strb_LSR_Rm_1, // 0x443
        gbaemu::gba::cpu::impl::sdt::opcode_strb_ASR_Rm_0, // 0x444
        gbaemu::gba::cpu::impl::sdt::opcode_strb_ASR_Rm_1, // 0x445
        gbaemu::gba::cpu::impl::sdt::opcode_strb_ROR_Rm_0, // 0x446
        gbaemu::gba::cpu::impl::sdt::opcode_strb_ROR_Rm_1, // 0x447
        gbaemu::gba::cpu::impl::sdt::opcode_strb_LSL_Rm_0, // 0x448
        NULL, // 0x449
        gbaemu::gba::cpu::impl::sdt::opcode_strb_LSR_Rm_0, // 0x44a
        NULL, // 0x44b
        gbaemu::gba::cpu::impl::sdt::opcode_strb_ASR_Rm_0, // 0x44c
        NULL, // 0x44d
        gbaemu::gba::cpu::impl::sdt::opcode_strb_ROR_Rm_0, // 0x44e
        NULL, // 0x44f
        gbaemu::gba::cpu::impl::sdt::opcode_ldrb_LSL_Rm_0, // 0x450
        gbaemu::gba::cpu::impl::sdt::opcode_ldrb_LSL_Rm_1, // 0x451
        gbaemu::gba::cpu::impl::sdt::opcode_ldrb_LSR_Rm_0, // 0x452
        gbaemu::gba::cpu::impl::sdt::opcode_ldrb_LSR_Rm_1, // 0x453
        gbaemu::gba::cpu::impl::sdt::opcode_ldrb_ASR_Rm_0, // 0x454
        gbaemu::gba::cpu::impl::sdt::opcode_ldrb_ASR_Rm_1, // 0x455
        gbaemu::gba::cpu::impl::sdt::opcode_ldrb_ROR_Rm_0, // 0x456
        gbaemu::gba::cpu::impl::sdt::opcode_ldrb_ROR_Rm_1, // 0x457
        gbaemu::gba::cpu::impl::sdt::opcode_ldrb_LSL_Rm_0, // 0x458
        NULL, // 0x459
        gbaemu::gba::cpu::impl::sdt::opcode_ldrb_LSR_Rm_0, // 0x45a
        NULL, // 0x45b
        gbaemu::gba::cpu::impl::sdt::opcode_ldrb_ASR_Rm_0, // 0x45c
        NULL, // 0x45d
        gbaemu::gba::cpu::impl::sdt::opcode_ldrb_ROR_Rm_0, // 0x45e
        NULL, // 0x45f
        NULL, // 0x460
        NULL, // 0x461
        NULL, // 0x462
        NULL, // 0x463
        NULL, // 0x464
        NULL, // 0x465
        NULL, // 0x466
        NULL, // 0x467
        NULL, // 0x468
        NULL, // 0x469
        NULL, // 0x46a
        NULL, // 0x46b
        NULL, // 0x46c
        NULL, // 0x46d
        NULL, // 0x46e
        NULL, // 0x46f
        NULL, // 0x470
        NULL, // 0x471
        NULL, // 0x472
        NULL, // 0x473
        NULL, // 0x474
        NULL, // 0x475
        NULL, // 0x476
        NULL, // 0x477
        NULL, // 0x478
        NULL, // 0x479
        NULL, // 0x47a
        NULL, // 0x47b
        NULL, // 0x47c
        NULL, // 0x47d
        NULL, // 0x47e
        NULL, // 0x47f
        gbaemu::gba::cpu::impl::sdt::opcode_stru_LSL_Rm_0, // 0x480
        gbaemu::gba::cpu::impl::sdt::opcode_stru_LSL_Rm_1, // 0x481
        gbaemu::gba::cpu::impl::sdt::opcode_stru_LSR_Rm_0, // 0x482
        gbaemu::gba::cpu::impl::sdt::opcode_stru_LSR_Rm_1, // 0x483
        gbaemu::gba::cpu::impl::sdt::opcode_stru_ASR_Rm_0, // 0x484
        gbaemu::gba::cpu::impl::sdt::opcode_stru_ASR_Rm_1, // 0x485
        gbaemu::gba::cpu::impl::sdt::opcode_stru_ROR_Rm_0, // 0x486
        gbaemu::gba::cpu::impl::sdt::opcode_stru_ROR_Rm_1, // 0x487
        gbaemu::gba::cpu::impl::sdt::opcode_stru_LSL_Rm_0, // 0x488
        NULL, // 0x489
        gbaemu::gba::cpu::impl::sdt::opcode_stru_LSR_Rm_0, // 0x48a
        NULL, // 0x48b
        gbaemu::gba::cpu::impl::sdt::opcode_stru_ASR_Rm_0, // 0x48c
        NULL, // 0x48d
        gbaemu::gba::cpu::impl::sdt::opcode_stru_ROR_Rm_0, // 0x48e
        NULL, // 0x48f
        gbaemu::gba::cpu::impl::sdt::opcode_ldru_LSL_Rm_0, // 0x490
        gbaemu::gba::cpu::impl::sdt::opcode_ldru_LSL_Rm_1, // 0x491
        gbaemu::gba::cpu::impl::sdt::opcode_ldru_LSR_Rm_0, // 0x492
        gbaemu::gba::cpu::impl::sdt::opcode_ldru_LSR_Rm_1, // 0x493
        gbaemu::gba::cpu::impl::sdt::opcode_ldru_ASR_Rm_0, // 0x494
        gbaemu::gba::cpu::impl::sdt::opcode_ldru_ASR_Rm_1, // 0x495
        gbaemu::gba::cpu::impl::sdt::opcode_ldru_ROR_Rm_0, // 0x496
        gbaemu::gba::cpu::impl::sdt::opcode_ldru_ROR_Rm_1, // 0x497
        gbaemu::gba::cpu::impl::sdt::opcode_ldru_LSL_Rm_0, // 0x498
        NULL, // 0x499
        gbaemu::gba::cpu::impl::sdt::opcode_ldru_LSR_Rm_0, // 0x49a
        NULL, // 0x49b
        gbaemu::gba::cpu::impl::sdt::opcode_ldru_ASR_Rm_0, // 0x49c
        NULL, // 0x49d
        gbaemu::gba::cpu::impl::sdt::opcode_ldru_ROR_Rm_0, // 0x49e
        NULL, // 0x49f
        NULL, // 0x4a0
        NULL, // 0x4a1
        NULL, // 0x4a2
        NULL, // 0x4a3
        NULL, // 0x4a4
        NULL, // 0x4a5
        NULL, // 0x4a6
        NULL, // 0x4a7
        NULL, // 0x4a8
        NULL, // 0x4a9
        NULL, // 0x4aa
        NULL, // 0x4ab
        NULL, // 0x4ac
        NULL, // 0x4ad
        NULL, // 0x4ae
        NULL, // 0x4af
        NULL, // 0x4b0
        NULL, // 0x4b1
        NULL, // 0x4b2
        NULL, // 0x4b3
        NULL, // 0x4b4
        NULL, // 0x4b5
        NULL, // 0x4b6
        NULL, // 0x4b7
        NULL, // 0x4b8
        NULL, // 0x4b9
        NULL, // 0x4ba
        NULL, // 0x4bb
        NULL, // 0x4bc
        NULL, // 0x4bd
        NULL, // 0x4be
        NULL, // 0x4bf
        gbaemu::gba::cpu::impl::sdt::opcode_strub_LSL_Rm_0, // 0x4c0
        gbaemu::gba::cpu::impl::sdt::opcode_strub_LSL_Rm_1, // 0x4c1
        gbaemu::gba::cpu::impl::sdt::opcode_strub_LSR_Rm_0, // 0x4c2
        gbaemu::gba::cpu::impl::sdt::opcode_strub_LSR_Rm_1, // 0x4c3
        gbaemu::gba::cpu::impl::sdt::opcode_strub_ASR_Rm_0, // 0x4c4
        gbaemu::gba::cpu::impl::sdt::opcode_strub_ASR_Rm_1, // 0x4c5
        gbaemu::gba::cpu::impl::sdt::opcode_strub_ROR_Rm_0, // 0x4c6
        gbaemu::gba::cpu::impl::sdt::opcode_strub_ROR_Rm_1, // 0x4c7
        gbaemu::gba::cpu::impl::sdt::opcode_strub_LSL_Rm_0, // 0x4c8
        NULL, // 0x4c9
        gbaemu::gba::cpu::impl::sdt::opcode_strub_LSR_Rm_0, // 0x4ca
        NULL, // 0x4cb
        gbaemu::gba::cpu::impl::sdt::opcode_strub_ASR_Rm_0, // 0x4cc
        NULL, // 0x4cd
        gbaemu::gba::cpu::impl::sdt::opcode_strub_ROR_Rm_0, // 0x4ce
        NULL, // 0x4cf
        gbaemu::gba::cpu::impl::sdt::opcode_ldrub_LSL_Rm_0, // 0x4d0
        gbaemu::gba::cpu::impl::sdt::opcode_ldrub_LSL_Rm_1, // 0x4d1
        gbaemu::gba::cpu::impl::sdt::opcode_ldrub_LSR_Rm_0, // 0x4d2
        gbaemu::gba::cpu::impl::sdt::opcode_ldrub_LSR_Rm_1, // 0x4d3
        gbaemu::gba::cpu::impl::sdt::opcode_ldrub_ASR_Rm_0, // 0x4d4
        gbaemu::gba::cpu::impl::sdt::opcode_ldrub_ASR_Rm_1, // 0x4d5
        gbaemu::gba::cpu::impl::sdt::opcode_ldrub_ROR_Rm_0, // 0x4d6
        gbaemu::gba::cpu::impl::sdt::opcode_ldrub_ROR_Rm_1, // 0x4d7
        gbaemu::gba::cpu::impl::sdt::opcode_ldrub_LSL_Rm_0, // 0x4d8
        NULL, // 0x4d9
        gbaemu::gba::cpu::impl::sdt::opcode_ldrub_LSR_Rm_0, // 0x4da
        NULL, // 0x4db
        gbaemu::gba::cpu::impl::sdt::opcode_ldrub_ASR_Rm_0, // 0x4dc
        NULL, // 0x4dd
        gbaemu::gba::cpu::impl::sdt::opcode_ldrub_ROR_Rm_0, // 0x4de
        NULL, // 0x4df
        NULL, // 0x4e0
        NULL, // 0x4e1
        NULL, // 0x4e2
        NULL, // 0x4e3
        NULL, // 0x4e4
        NULL, // 0x4e5
        NULL, // 0x4e6
        NULL, // 0x4e7
        NULL, // 0x4e8
        NULL, // 0x4e9
        NULL, // 0x4ea
        NULL, // 0x4eb
        NULL, // 0x4ec
        NULL, // 0x4ed
        NULL, // 0x4ee
        NULL, // 0x4ef
        NULL, // 0x4f0
        NULL, // 0x4f1
        NULL, // 0x4f2
        NULL, // 0x4f3
        NULL, // 0x4f4
        NULL, // 0x4f5
        NULL, // 0x4f6
        NULL, // 0x4f7
        NULL, // 0x4f8
        NULL, // 0x4f9
        NULL, // 0x4fa
        NULL, // 0x4fb
        NULL, // 0x4fc
        NULL, // 0x4fd
        NULL, // 0x4fe
        NULL, // 0x4ff
        gbaemu::gba::cpu::impl::sdt::opcode_strp_LSL_Rm_0, // 0x500
        gbaemu::gba::cpu::impl::sdt::opcode_strp_LSL_Rm_1, // 0x501
        gbaemu::gba::cpu::impl::sdt::opcode_strp_LSR_Rm_0, // 0x502
        gbaemu::gba::cpu::impl::sdt::opcode_strp_LSR_Rm_1, // 0x503
        gbaemu::gba::cpu::impl::sdt::opcode_strp_ASR_Rm_0, // 0x504
        gbaemu::gba::cpu::impl::sdt::opcode_strp_ASR_Rm_1, // 0x505
        gbaemu::gba::cpu::impl::sdt::opcode_strp_ROR_Rm_0, // 0x506
        gbaemu::gba::cpu::impl::sdt::opcode_strp_ROR_Rm_1, // 0x507
        gbaemu::gba::cpu::impl::sdt::opcode_strp_LSL_Rm_0, // 0x508
        NULL, // 0x509
        gbaemu::gba::cpu::impl::sdt::opcode_strp_LSR_Rm_0, // 0x50a
        NULL, // 0x50b
        gbaemu::gba::cpu::impl::sdt::opcode_strp_ASR_Rm_0, // 0x50c
        NULL, // 0x50d
        gbaemu::gba::cpu::impl::sdt::opcode_strp_ROR_Rm_0, // 0x50e
        NULL, // 0x50f
        gbaemu::gba::cpu::impl::sdt::opcode_ldrp_LSL_Rm_0, // 0x510
        gbaemu::gba::cpu::impl::sdt::opcode_ldrp_LSL_Rm_1, // 0x511
        gbaemu::gba::cpu::impl::sdt::opcode_ldrp_LSR_Rm_0, // 0x512
        gbaemu::gba::cpu::impl::sdt::opcode_ldrp_LSR_Rm_1, // 0x513
        gbaemu::gba::cpu::impl::sdt::opcode_ldrp_ASR_Rm_0, // 0x514
        gbaemu::gba::cpu::impl::sdt::opcode_ldrp_ASR_Rm_1, // 0x515
        gbaemu::gba::cpu::impl::sdt::opcode_ldrp_ROR_Rm_0, // 0x516
        gbaemu::gba::cpu::impl::sdt::opcode_ldrp_ROR_Rm_1, // 0x517
        gbaemu::gba::cpu::impl::sdt::opcode_ldrp_LSL_Rm_0, // 0x518
        NULL, // 0x519
        gbaemu::gba::cpu::impl::sdt::opcode_ldrp_LSR_Rm_0, // 0x51a
        NULL, // 0x51b
        gbaemu::gba::cpu::impl::sdt::opcode_ldrp_ASR_Rm_0, // 0x51c
        NULL, // 0x51d
        gbaemu::gba::cpu::impl::sdt::opcode_ldrp_ROR_Rm_0, // 0x51e
        NULL, // 0x51f
        gbaemu::gba::cpu::impl::sdt::opcode_strpw_LSL_Rm_0, // 0x520
        gbaemu::gba::cpu::impl::sdt::opcode_strpw_LSL_Rm_1, // 0x521
        gbaemu::gba::cpu::impl::sdt::opcode_strpw_LSR_Rm_0, // 0x522
        gbaemu::gba::cpu::impl::sdt::opcode_strpw_LSR_Rm_1, // 0x523
        gbaemu::gba::cpu::impl::sdt::opcode_strpw_ASR_Rm_0, // 0x524
        gbaemu::gba::cpu::impl::sdt::opcode_strpw_ASR_Rm_1, // 0x525
        gbaemu::gba::cpu::impl::sdt::opcode_strpw_ROR_Rm_0, // 0x526
        gbaemu::gba::cpu::impl::sdt::opcode_strpw_ROR_Rm_1, // 0x527
        gbaemu::gba::cpu::impl::sdt::opcode_strpw_LSL_Rm_0, // 0x528
        NULL, // 0x529
        gbaemu::gba::cpu::impl::sdt::opcode_strpw_LSR_Rm_0, // 0x52a
        NULL, // 0x52b
        gbaemu::gba::cpu::impl::sdt::opcode_strpw_ASR_Rm_0, // 0x52c
        NULL, // 0x52d
        gbaemu::gba::cpu::impl::sdt::opcode_strpw_ROR_Rm_0, // 0x52e
        NULL, // 0x52f
        gbaemu::gba::cpu::impl::sdt::opcode_ldrpw_LSL_Rm_0, // 0x530
        gbaemu::gba::cpu::impl::sdt::opcode_ldrpw_LSL_Rm_1, // 0x531
        gbaemu::gba::cpu::impl::sdt::opcode_ldrpw_LSR_Rm_0, // 0x532
        gbaemu::gba::cpu::impl::sdt::opcode_ldrpw_LSR_Rm_1, // 0x533
        gbaemu::gba::cpu::impl::sdt::opcode_ldrpw_ASR_Rm_0, // 0x534
        gbaemu::gba::cpu::impl::sdt::opcode_ldrpw_ASR_Rm_1, // 0x535
        gbaemu::gba::cpu::impl::sdt::opcode_ldrpw_ROR_Rm_0, // 0x536
        gbaemu::gba::cpu::impl::sdt::opcode_ldrpw_ROR_Rm_1, // 0x537
        gbaemu::gba::cpu::impl::sdt::opcode_ldrpw_LSL_Rm_0, // 0x538
        NULL, // 0x539
        gbaemu::gba::cpu::impl::sdt::opcode_ldrpw_LSR_Rm_0, // 0x53a
        NULL, // 0x53b
        gbaemu::gba::cpu::impl::sdt::opcode_ldrpw_ASR_Rm_0, // 0x53c
        NULL, // 0x53d
        gbaemu::gba::cpu::impl::sdt::opcode_ldrpw_ROR_Rm_0, // 0x53e
        NULL, // 0x53f
        gbaemu::gba::cpu::impl::sdt::opcode_strpb_LSL_Rm_0, // 0x540
        gbaemu::gba::cpu::impl::sdt::opcode_strpb_LSL_Rm_1, // 0x541
        gbaemu::gba::cpu::impl::sdt::opcode_strpb_LSR_Rm_0, // 0x542
        gbaemu::gba::cpu::impl::sdt::opcode_strpb_LSR_Rm_1, // 0x543
        gbaemu::gba::cpu::impl::sdt::opcode_strpb_ASR_Rm_0, // 0x544
        gbaemu::gba::cpu::impl::sdt::opcode_strpb_ASR_Rm_1, // 0x545
        gbaemu::gba::cpu::impl::sdt::opcode_strpb_ROR_Rm_0, // 0x546
        gbaemu::gba::cpu::impl::sdt::opcode_strpb_ROR_Rm_1, // 0x547
        gbaemu::gba::cpu::impl::sdt::opcode_strpb_LSL_Rm_0, // 0x548
        NULL, // 0x549
        gbaemu::gba::cpu::impl::sdt::opcode_strpb_LSR_Rm_0, // 0x54a
        NULL, // 0x54b
        gbaemu::gba::cpu::impl::sdt::opcode_strpb_ASR_Rm_0, // 0x54c
        NULL, // 0x54d
        gbaemu::gba::cpu::impl::sdt::opcode_strpb_ROR_Rm_0, // 0x54e
        NULL, // 0x54f
        gbaemu::gba::cpu::impl::sdt::opcode_ldrpb_LSL_Rm_0, // 0x550
        gbaemu::gba::cpu::impl::sdt::opcode_ldrpb_LSL_Rm_1, // 0x551
        gbaemu::gba::cpu::impl::sdt::opcode_ldrpb_LSR_Rm_0, // 0x552
        gbaemu::gba::cpu::impl::sdt::opcode_ldrpb_LSR_Rm_1, // 0x553
        gbaemu::gba::cpu::impl::sdt::opcode_ldrpb_ASR_Rm_0, // 0x554
        gbaemu::gba::cpu::impl::sdt::opcode_ldrpb_ASR_Rm_1, // 0x555
        gbaemu::gba::cpu::impl::sdt::opcode_ldrpb_ROR_Rm_0, // 0x556
        gbaemu::gba::cpu::impl::sdt::opcode_ldrpb_ROR_Rm_1, // 0x557
        gbaemu::gba::cpu::impl::sdt::opcode_ldrpb_LSL_Rm_0, // 0x558
        NULL, // 0x559
        gbaemu::gba::cpu::impl::sdt::opcode_ldrpb_LSR_Rm_0, // 0x55a
        NULL, // 0x55b
        gbaemu::gba::cpu::impl::sdt::opcode_ldrpb_ASR_Rm_0, // 0x55c
        NULL, // 0x55d
        gbaemu::gba::cpu::impl::sdt::opcode_ldrpb_ROR_Rm_0, // 0x55e
        NULL, // 0x55f
        gbaemu::gba::cpu::impl::sdt::opcode_strpbw_LSL_Rm_0, // 0x560
        gbaemu::gba::cpu::impl::sdt::opcode_strpbw_LSL_Rm_1, // 0x561
        gbaemu::gba::cpu::impl::sdt::opcode_strpbw_LSR_Rm_0, // 0x562
        gbaemu::gba::cpu::impl::sdt::opcode_strpbw_LSR_Rm_1, // 0x563
        gbaemu::gba::cpu::impl::sdt::opcode_strpbw_ASR_Rm_0, // 0x564
        gbaemu::gba::cpu::impl::sdt::opcode_strpbw_ASR_Rm_1, // 0x565
        gbaemu::gba::cpu::impl::sdt::opcode_strpbw_ROR_Rm_0, // 0x566
        gbaemu::gba::cpu::impl::sdt::opcode_strpbw_ROR_Rm_1, // 0x567
        gbaemu::gba::cpu::impl::sdt::opcode_strpbw_LSL_Rm_0, // 0x568
        NULL, // 0x569
        gbaemu::gba::cpu::impl::sdt::opcode_strpbw_LSR_Rm_0, // 0x56a
        NULL, // 0x56b
        gbaemu::gba::cpu::impl::sdt::opcode_strpbw_ASR_Rm_0, // 0x56c
        NULL, // 0x56d
        gbaemu::gba::cpu::impl::sdt::opcode_strpbw_ROR_Rm_0, // 0x56e
        NULL, // 0x56f
        gbaemu::gba::cpu::impl::sdt::opcode_ldrpbw_LSL_Rm_0, // 0x570
        gbaemu::gba::cpu::impl::sdt::opcode_ldrpbw_LSL_Rm_1, // 0x571
        gbaemu::gba::cpu::impl::sdt::opcode_ldrpbw_LSR_Rm_0, // 0x572
        gbaemu::gba::cpu::impl::sdt::opcode_ldrpbw_LSR_Rm_1, // 0x573
        gbaemu::gba::cpu::impl::sdt::opcode_ldrpbw_ASR_Rm_0, // 0x574
        gbaemu::gba::cpu::impl::sdt::opcode_ldrpbw_ASR_Rm_1, // 0x575
        gbaemu::gba::cpu::impl::sdt::opcode_ldrpbw_ROR_Rm_0, // 0x576
        gbaemu::gba::cpu::impl::sdt::opcode_ldrpbw_ROR_Rm_1, // 0x577
        gbaemu::gba::cpu::impl::sdt::opcode_ldrpbw_LSL_Rm_0, // 0x578
        NULL, // 0x579
        gbaemu::gba::cpu::impl::sdt::opcode_ldrpbw_LSR_Rm_0, // 0x57a
        NULL, // 0x57b
        gbaemu::gba::cpu::impl::sdt::opcode_ldrpbw_ASR_Rm_0, // 0x57c
        NULL, // 0x57d
        gbaemu::gba::cpu::impl::sdt::opcode_ldrpbw_ROR_Rm_0, // 0x57e
        NULL, // 0x57f
        gbaemu::gba::cpu::impl::sdt::opcode_strpu_LSL_Rm_0, // 0x580
        gbaemu::gba::cpu::impl::sdt::opcode_strpu_LSL_Rm_1, // 0x581
        gbaemu::gba::cpu::impl::sdt::opcode_strpu_LSR_Rm_0, // 0x582
        gbaemu::gba::cpu::impl::sdt::opcode_strpu_LSR_Rm_1, // 0x583
        gbaemu::gba::cpu::impl::sdt::opcode_strpu_ASR_Rm_0, // 0x584
        gbaemu::gba::cpu::impl::sdt::opcode_strpu_ASR_Rm_1, // 0x585
        gbaemu::gba::cpu::impl::sdt::opcode_strpu_ROR_Rm_0, // 0x586
        gbaemu::gba::cpu::impl::sdt::opcode_strpu_ROR_Rm_1, // 0x587
        gbaemu::gba::cpu::impl::sdt::opcode_strpu_LSL_Rm_0, // 0x588
        NULL, // 0x589
        gbaemu::gba::cpu::impl::sdt::opcode_strpu_LSR_Rm_0, // 0x58a
        NULL, // 0x58b
        gbaemu::gba::cpu::impl::sdt::opcode_strpu_ASR_Rm_0, // 0x58c
        NULL, // 0x58d
        gbaemu::gba::cpu::impl::sdt::opcode_strpu_ROR_Rm_0, // 0x58e
        NULL, // 0x58f
        gbaemu::gba::cpu::impl::sdt::opcode_ldrpu_LSL_Rm_0, // 0x590
        gbaemu::gba::cpu::impl::sdt::opcode_ldrpu_LSL_Rm_1, // 0x591
        gbaemu::gba::cpu::impl::sdt::opcode_ldrpu_LSR_Rm_0, // 0x592
        gbaemu::gba::cpu::impl::sdt::opcode_ldrpu_LSR_Rm_1, // 0x593
        gbaemu::gba::cpu::impl::sdt::opcode_ldrpu_ASR_Rm_0, // 0x594
        gbaemu::gba::cpu::impl::sdt::opcode_ldrpu_ASR_Rm_1, // 0x595
        gbaemu::gba::cpu::impl::sdt::opcode_ldrpu_ROR_Rm_0, // 0x596
        gbaemu::gba::cpu::impl::sdt::opcode_ldrpu_ROR_Rm_1, // 0x597
        gbaemu::gba::cpu::impl::sdt::opcode_ldrpu_LSL_Rm_0, // 0x598
        NULL, // 0x599
        gbaemu::gba::cpu::impl::sdt::opcode_ldrpu_LSR_Rm_0, // 0x59a
        NULL, // 0x59b
        gbaemu::gba::cpu::impl::sdt::opcode_ldrpu_ASR_Rm_0, // 0x59c
        NULL, // 0x59d
        gbaemu::gba::cpu::impl::sdt::opcode_ldrpu_ROR_Rm_0, // 0x59e
        NULL, // 0x59f
        gbaemu::gba::cpu::impl::sdt::opcode_strpuw_LSL_Rm_0, // 0x5a0
        gbaemu::gba::cpu::impl::sdt::opcode_strpuw_LSL_Rm_1, // 0x5a1
        gbaemu::gba::cpu::impl::sdt::opcode_strpuw_LSR_Rm_0, // 0x5a2
        gbaemu::gba::cpu::impl::sdt::opcode_strpuw_LSR_Rm_1, // 0x5a3
        gbaemu::gba::cpu::impl::sdt::opcode_strpuw_ASR_Rm_0, // 0x5a4
        gbaemu::gba::cpu::impl::sdt::opcode_strpuw_ASR_Rm_1, // 0x5a5
        gbaemu::gba::cpu::impl::sdt::opcode_strpuw_ROR_Rm_0, // 0x5a6
        gbaemu::gba::cpu::impl::sdt::opcode_strpuw_ROR_Rm_1, // 0x5a7
        gbaemu::gba::cpu::impl::sdt::opcode_strpuw_LSL_Rm_0, // 0x5a8
        NULL, // 0x5a9
        gbaemu::gba::cpu::impl::sdt::opcode_strpuw_LSR_Rm_0, // 0x5aa
        NULL, // 0x5ab
        gbaemu::gba::cpu::impl::sdt::opcode_strpuw_ASR_Rm_0, // 0x5ac
        NULL, // 0x5ad
        gbaemu::gba::cpu::impl::sdt::opcode_strpuw_ROR_Rm_0, // 0x5ae
        NULL, // 0x5af
        gbaemu::gba::cpu::impl::sdt::opcode_ldrpuw_LSL_Rm_0, // 0x5b0
        gbaemu::gba::cpu::impl::sdt::opcode_ldrpuw_LSL_Rm_1, // 0x5b1
        gbaemu::gba::cpu::impl::sdt::opcode_ldrpuw_LSR_Rm_0, // 0x5b2
        gbaemu::gba::cpu::impl::sdt::opcode_ldrpuw_LSR_Rm_1, // 0x5b3
        gbaemu::gba::cpu::impl::sdt::opcode_ldrpuw_ASR_Rm_0, // 0x5b4
        gbaemu::gba::cpu::impl::sdt::opcode_ldrpuw_ASR_Rm_1, // 0x5b5
        gbaemu::gba::cpu::impl::sdt::opcode_ldrpuw_ROR_Rm_0, // 0x5b6
        gbaemu::gba::cpu::impl::sdt::opcode_ldrpuw_ROR_Rm_1, // 0x5b7
        gbaemu::gba::cpu::impl::sdt::opcode_ldrpuw_LSL_Rm_0, // 0x5b8
        NULL, // 0x5b9
        gbaemu::gba::cpu::impl::sdt::opcode_ldrpuw_LSR_Rm_0, // 0x5ba
        NULL, // 0x5bb
        gbaemu::gba::cpu::impl::sdt::opcode_ldrpuw_ASR_Rm_0, // 0x5bc
        NULL, // 0x5bd
        gbaemu::gba::cpu::impl::sdt::opcode_ldrpuw_ROR_Rm_0, // 0x5be
        NULL, // 0x5bf
        gbaemu::gba::cpu::impl::sdt::opcode_strpub_LSL_Rm_0, // 0x5c0
        gbaemu::gba::cpu::impl::sdt::opcode_strpub_LSL_Rm_1, // 0x5c1
        gbaemu::gba::cpu::impl::sdt::opcode_strpub_LSR_Rm_0, // 0x5c2
        gbaemu::gba::cpu::impl::sdt::opcode_strpub_LSR_Rm_1, // 0x5c3
        gbaemu::gba::cpu::impl::sdt::opcode_strpub_ASR_Rm_0, // 0x5c4
        gbaemu::gba::cpu::impl::sdt::opcode_strpub_ASR_Rm_1, // 0x5c5
        gbaemu::gba::cpu::impl::sdt::opcode_strpub_ROR_Rm_0, // 0x5c6
        gbaemu::gba::cpu::impl::sdt::opcode_strpub_ROR_Rm_1, // 0x5c7
        gbaemu::gba::cpu::impl::sdt::opcode_strpub_LSL_Rm_0, // 0x5c8
        NULL, // 0x5c9
        gbaemu::gba::cpu::impl::sdt::opcode_strpub_LSR_Rm_0, // 0x5ca
        NULL, // 0x5cb
        gbaemu::gba::cpu::impl::sdt::opcode_strpub_ASR_Rm_0, // 0x5cc
        NULL, // 0x5cd
        gbaemu::gba::cpu::impl::sdt::opcode_strpub_ROR_Rm_0, // 0x5ce
        NULL, // 0x5cf
        gbaemu::gba::cpu::impl::sdt::opcode_ldrpub_LSL_Rm_0, // 0x5d0
        gbaemu::gba::cpu::impl::sdt::opcode_ldrpub_LSL_Rm_1, // 0x5d1
        gbaemu::gba::cpu::impl::sdt::opcode_ldrpub_LSR_Rm_0, // 0x5d2
        gbaemu::gba::cpu::impl::sdt::opcode_ldrpub_LSR_Rm_1, // 0x5d3
        gbaemu::gba::cpu::impl::sdt::opcode_ldrpub_ASR_Rm_0, // 0x5d4
        gbaemu::gba::cpu::impl::sdt::opcode_ldrpub_ASR_Rm_1, // 0x5d5
        gbaemu::gba::cpu::impl::sdt::opcode_ldrpub_ROR_Rm_0, // 0x5d6
        gbaemu::gba::cpu::impl::sdt::opcode_ldrpub_ROR_Rm_1, // 0x5d7
        gbaemu::gba::cpu::impl::sdt::opcode_ldrpub_LSL_Rm_0, // 0x5d8
        NULL, // 0x5d9
        gbaemu::gba::cpu::impl::sdt::opcode_ldrpub_LSR_Rm_0, // 0x5da
        NULL, // 0x5db
        gbaemu::gba::cpu::impl::sdt::opcode_ldrpub_ASR_Rm_0, // 0x5dc
        NULL, // 0x5dd
        gbaemu::gba::cpu::impl::sdt::opcode_ldrpub_ROR_Rm_0, // 0x5de
        NULL, // 0x5df
        gbaemu::gba::cpu::impl::sdt::opcode_strpubw_LSL_Rm_0, // 0x5e0
        gbaemu::gba::cpu::impl::sdt::opcode_strpubw_LSL_Rm_1, // 0x5e1
        gbaemu::gba::cpu::impl::sdt::opcode_strpubw_LSR_Rm_0, // 0x5e2
        gbaemu::gba::cpu::impl::sdt::opcode_strpubw_LSR_Rm_1, // 0x5e3
        gbaemu::gba::cpu::impl::sdt::opcode_strpubw_ASR_Rm_0, // 0x5e4
        gbaemu::gba::cpu::impl::sdt::opcode_strpubw_ASR_Rm_1, // 0x5e5
        gbaemu::gba::cpu::impl::sdt::opcode_strpubw_ROR_Rm_0, // 0x5e6
        gbaemu::gba::cpu::impl::sdt::opcode_strpubw_ROR_Rm_1, // 0x5e7
        gbaemu::gba::cpu::impl::sdt::opcode_strpubw_LSL_Rm_0, // 0x5e8
        NULL, // 0x5e9
        gbaemu::gba::cpu::impl::sdt::opcode_strpubw_LSR_Rm_0, // 0x5ea
        NULL, // 0x5eb
        gbaemu::gba::cpu::impl::sdt::opcode_strpubw_ASR_Rm_0, // 0x5ec
        NULL, // 0x5ed
        gbaemu::gba::cpu::impl::sdt::opcode_strpubw_ROR_Rm_0, // 0x5ee
        NULL, // 0x5ef
        gbaemu::gba::cpu::impl::sdt::opcode_ldrpubw_LSL_Rm_0, // 0x5f0
        gbaemu::gba::cpu::impl::sdt::opcode_ldrpubw_LSL_Rm_1, // 0x5f1
        gbaemu::gba::cpu::impl::sdt::opcode_ldrpubw_LSR_Rm_0, // 0x5f2
        gbaemu::gba::cpu::impl::sdt::opcode_ldrpubw_LSR_Rm_1, // 0x5f3
        gbaemu::gba::cpu::impl::sdt::opcode_ldrpubw_ASR_Rm_0, // 0x5f4
        gbaemu::gba::cpu::impl::sdt::opcode_ldrpubw_ASR_Rm_1, // 0x5f5
        gbaemu::gba::cpu::impl::sdt::opcode_ldrpubw_ROR_Rm_0, // 0x5f6
        gbaemu::gba::cpu::impl::sdt::opcode_ldrpubw_ROR_Rm_1, // 0x5f7
        gbaemu::gba::cpu::impl::sdt::opcode_ldrpubw_LSL_Rm_0, // 0x5f8
        NULL, // 0x5f9
        gbaemu::gba::cpu::impl::sdt::opcode_ldrpubw_LSR_Rm_0, // 0x5fa
        NULL, // 0x5fb
        gbaemu::gba::cpu::impl::sdt::opcode_ldrpubw_ASR_Rm_0, // 0x5fc
        NULL, // 0x5fd
        gbaemu::gba::cpu::impl::sdt::opcode_ldrpubw_ROR_Rm_0, // 0x5fe
        NULL, // 0x5ff
        REP16(gbaemu::gba::cpu::impl::sdt::opcode_str_Immediate), // 0x600
        REP16(gbaemu::gba::cpu::impl::sdt::opcode_ldr_Immediate), // 0x610
        NULL, // 0x620
        NULL, // 0x621
        NULL, // 0x622
        NULL, // 0x623
        NULL, // 0x624
        NULL, // 0x625
        NULL, // 0x626
        NULL, // 0x627
        NULL, // 0x628
        NULL, // 0x629
        NULL, // 0x62a
        NULL, // 0x62b
        NULL, // 0x62c
        NULL, // 0x62d
        NULL, // 0x62e
        NULL, // 0x62f
        NULL, // 0x630
        NULL, // 0x631
        NULL, // 0x632
        NULL, // 0x633
        NULL, // 0x634
        NULL, // 0x635
        NULL, // 0x636
        NULL, // 0x637
        NULL, // 0x638
        NULL, // 0x639
        NULL, // 0x63a
        NULL, // 0x63b
        NULL, // 0x63c
        NULL, // 0x63d
        NULL, // 0x63e
        NULL, // 0x63f
        REP16(gbaemu::gba::cpu::impl::sdt::opcode_strb_Immediate), // 0x640
        REP16(gbaemu::gba::cpu::impl::sdt::opcode_ldrb_Immediate), // 0x650
        NULL, // 0x660
        NULL, // 0x661
        NULL, // 0x662
        NULL, // 0x663
        NULL, // 0x664
        NULL, // 0x665
        NULL, // 0x666
        NULL, // 0x667
        NULL, // 0x668
        NULL, // 0x669
        NULL, // 0x66a
        NULL, // 0x66b
        NULL, // 0x66c
        NULL, // 0x66d
        NULL, // 0x66e
        NULL, // 0x66f
        NULL, // 0x670
        NULL, // 0x671
        NULL, // 0x672
        NULL, // 0x673
        NULL, // 0x674
        NULL, // 0x675
        NULL, // 0x676
        NULL, // 0x677
        NULL, // 0x678
        NULL, // 0x679
        NULL, // 0x67a
        NULL, // 0x67b
        NULL, // 0x67c
        NULL, // 0x67d
        NULL, // 0x67e
        NULL, // 0x67f
        REP16(gbaemu::gba::cpu::impl::sdt::opcode_stru_Immediate), // 0x680
        REP16(gbaemu::gba::cpu::impl::sdt::opcode_ldru_Immediate), // 0x690
        NULL, // 0x6a0
        NULL, // 0x6a1
        NULL, // 0x6a2
        NULL, // 0x6a3
        NULL, // 0x6a4
        NULL, // 0x6a5
        NULL, // 0x6a6
        NULL, // 0x6a7
        NULL, // 0x6a8
        NULL, // 0x6a9
        NULL, // 0x6aa
        NULL, // 0x6ab
        NULL, // 0x6ac
        NULL, // 0x6ad
        NULL, // 0x6ae
        NULL, // 0x6af
        NULL, // 0x6b0
        NULL, // 0x6b1
        NULL, // 0x6b2
        NULL, // 0x6b3
        NULL, // 0x6b4
        NULL, // 0x6b5
        NULL, // 0x6b6
        NULL, // 0x6b7
        NULL, // 0x6b8
        NULL, // 0x6b9
        NULL, // 0x6ba
        NULL, // 0x6bb
        NULL, // 0x6bc
        NULL, // 0x6bd
        NULL, // 0x6be
        NULL, // 0x6bf
        REP16(gbaemu::gba::cpu::impl::sdt::opcode_strub_Immediate), // 0x6c0
        REP16(gbaemu::gba::cpu::impl::sdt::opcode_strub_Immediate), // 0x6d0
        NULL, // 0x6e0
        NULL, // 0x6e1
        NULL, // 0x6e2
        NULL, // 0x6e3
        NULL, // 0x6e4
        NULL, // 0x6e5
        NULL, // 0x6e6
        NULL, // 0x6e7
        NULL, // 0x6e8
        NULL, // 0x6e9
        NULL, // 0x6ea
        NULL, // 0x6eb
        NULL, // 0x6ec
        NULL, // 0x6ed
        NULL, // 0x6ee
        NULL, // 0x6ef
        NULL, // 0x6f0
        NULL, // 0x6f1
        NULL, // 0x6f2
        NULL, // 0x6f3
        NULL, // 0x6f4
        NULL, // 0x6f5
        NULL, // 0x6f6
        NULL, // 0x6f7
        NULL, // 0x6f8
        NULL, // 0x6f9
        NULL, // 0x6fa
        NULL, // 0x6fb
        NULL, // 0x6fc
        NULL, // 0x6fd
        NULL, // 0x6fe
        NULL, // 0x6ff
        REP16(gbaemu::gba::cpu::impl::sdt::opcode_strp_Immediate), // 0x700
        REP16(gbaemu::gba::cpu::impl::sdt::opcode_ldrp_Immediate), // 0x710
        REP16(gbaemu::gba::cpu::impl::sdt::opcode_strpw_Immediate), // 0x720
        REP16(gbaemu::gba::cpu::impl::sdt::opcode_ldrpw_Immediate), // 0x730
        REP16(gbaemu::gba::cpu::impl::sdt::opcode_strpb_Immediate), // 0x740
        REP16(gbaemu::gba::cpu::impl::sdt::opcode_ldrpb_Immediate), // 0x750
        REP16(gbaemu::gba::cpu::impl::sdt::opcode_strpbw_Immediate), // 0x760
        REP16(gbaemu::gba::cpu::impl::sdt::opcode_ldrpbw_Immediate), // 0x770
        REP16(gbaemu::gba::cpu::impl::sdt::opcode_strpu_Immediate), // 0x780
        REP16(gbaemu::gba::cpu::impl::sdt::opcode_ldrpu_Immediate), // 0x790
        REP16(gbaemu::gba::cpu::impl::sdt::opcode_strpuw_Immediate), // 0x7a0
        REP16(gbaemu::gba::cpu::impl::sdt::opcode_ldrpuw_Immediate), // 0x7b0
        REP16(gbaemu::gba::cpu::impl::sdt::opcode_strpub_Immediate), // 0x7c0
        REP16(gbaemu::gba::cpu::impl::sdt::opcode_ldrpub_Immediate), // 0x7d0
        REP16(gbaemu::gba::cpu::impl::sdt::opcode_strpubw_Immediate), // 0x7e0
        REP16(gbaemu::gba::cpu::impl::sdt::opcode_ldrpubw_Immediate), // 0x7f0
        NULL, // 0x800
        NULL, // 0x801
        NULL, // 0x802
        NULL, // 0x803
        NULL, // 0x804
        NULL, // 0x805
        NULL, // 0x806
        NULL, // 0x807
        NULL, // 0x808
        NULL, // 0x809
        NULL, // 0x80a
        NULL, // 0x80b
        NULL, // 0x80c
        NULL, // 0x80d
        NULL, // 0x80e
        NULL, // 0x80f
        NULL, // 0x810
        NULL, // 0x811
        NULL, // 0x812
        NULL, // 0x813
        NULL, // 0x814
        NULL, // 0x815
        NULL, // 0x816
        NULL, // 0x817
        NULL, // 0x818
        NULL, // 0x819
        NULL, // 0x81a
        NULL, // 0x81b
        NULL, // 0x81c
        NULL, // 0x81d
        NULL, // 0x81e
        NULL, // 0x81f
        NULL, // 0x820
        NULL, // 0x821
        NULL, // 0x822
        NULL, // 0x823
        NULL, // 0x824
        NULL, // 0x825
        NULL, // 0x826
        NULL, // 0x827
        NULL, // 0x828
        NULL, // 0x829
        NULL, // 0x82a
        NULL, // 0x82b
        NULL, // 0x82c
        NULL, // 0x82d
        NULL, // 0x82e
        NULL, // 0x82f
        NULL, // 0x830
        NULL, // 0x831
        NULL, // 0x832
        NULL, // 0x833
        NULL, // 0x834
        NULL, // 0x835
        NULL, // 0x836
        NULL, // 0x837
        NULL, // 0x838
        NULL, // 0x839
        NULL, // 0x83a
        NULL, // 0x83b
        NULL, // 0x83c
        NULL, // 0x83d
        NULL, // 0x83e
        NULL, // 0x83f
        NULL, // 0x840
        NULL, // 0x841
        NULL, // 0x842
        NULL, // 0x843
        NULL, // 0x844
        NULL, // 0x845
        NULL, // 0x846
        NULL, // 0x847
        NULL, // 0x848
        NULL, // 0x849
        NULL, // 0x84a
        NULL, // 0x84b
        NULL, // 0x84c
        NULL, // 0x84d
        NULL, // 0x84e
        NULL, // 0x84f
        NULL, // 0x850
        NULL, // 0x851
        NULL, // 0x852
        NULL, // 0x853
        NULL, // 0x854
        NULL, // 0x855
        NULL, // 0x856
        NULL, // 0x857
        NULL, // 0x858
        NULL, // 0x859
        NULL, // 0x85a
        NULL, // 0x85b
        NULL, // 0x85c
        NULL, // 0x85d
        NULL, // 0x85e
        NULL, // 0x85f
        NULL, // 0x860
        NULL, // 0x861
        NULL, // 0x862
        NULL, // 0x863
        NULL, // 0x864
        NULL, // 0x865
        NULL, // 0x866
        NULL, // 0x867
        NULL, // 0x868
        NULL, // 0x869
        NULL, // 0x86a
        NULL, // 0x86b
        NULL, // 0x86c
        NULL, // 0x86d
        NULL, // 0x86e
        NULL, // 0x86f
        NULL, // 0x870
        NULL, // 0x871
        NULL, // 0x872
        NULL, // 0x873
        NULL, // 0x874
        NULL, // 0x875
        NULL, // 0x876
        NULL, // 0x877
        NULL, // 0x878
        NULL, // 0x879
        NULL, // 0x87a
        NULL, // 0x87b
        NULL, // 0x87c
        NULL, // 0x87d
        NULL, // 0x87e
        NULL, // 0x87f
        NULL, // 0x880
        NULL, // 0x881
        NULL, // 0x882
        NULL, // 0x883
        NULL, // 0x884
        NULL, // 0x885
        NULL, // 0x886
        NULL, // 0x887
        NULL, // 0x888
        NULL, // 0x889
        NULL, // 0x88a
        NULL, // 0x88b
        NULL, // 0x88c
        NULL, // 0x88d
        NULL, // 0x88e
        NULL, // 0x88f
        NULL, // 0x890
        NULL, // 0x891
        NULL, // 0x892
        NULL, // 0x893
        NULL, // 0x894
        NULL, // 0x895
        NULL, // 0x896
        NULL, // 0x897
        NULL, // 0x898
        NULL, // 0x899
        NULL, // 0x89a
        NULL, // 0x89b
        NULL, // 0x89c
        NULL, // 0x89d
        NULL, // 0x89e
        NULL, // 0x89f
        NULL, // 0x8a0
        NULL, // 0x8a1
        NULL, // 0x8a2
        NULL, // 0x8a3
        NULL, // 0x8a4
        NULL, // 0x8a5
        NULL, // 0x8a6
        NULL, // 0x8a7
        NULL, // 0x8a8
        NULL, // 0x8a9
        NULL, // 0x8aa
        NULL, // 0x8ab
        NULL, // 0x8ac
        NULL, // 0x8ad
        NULL, // 0x8ae
        NULL, // 0x8af
        NULL, // 0x8b0
        NULL, // 0x8b1
        NULL, // 0x8b2
        NULL, // 0x8b3
        NULL, // 0x8b4
        NULL, // 0x8b5
        NULL, // 0x8b6
        NULL, // 0x8b7
        NULL, // 0x8b8
        NULL, // 0x8b9
        NULL, // 0x8ba
        NULL, // 0x8bb
        NULL, // 0x8bc
        NULL, // 0x8bd
        NULL, // 0x8be
        NULL, // 0x8bf
        NULL, // 0x8c0
        NULL, // 0x8c1
        NULL, // 0x8c2
        NULL, // 0x8c3
        NULL, // 0x8c4
        NULL, // 0x8c5
        NULL, // 0x8c6
        NULL, // 0x8c7
        NULL, // 0x8c8
        NULL, // 0x8c9
        NULL, // 0x8ca
        NULL, // 0x8cb
        NULL, // 0x8cc
        NULL, // 0x8cd
        NULL, // 0x8ce
        NULL, // 0x8cf
        NULL, // 0x8d0
        NULL, // 0x8d1
        NULL, // 0x8d2
        NULL, // 0x8d3
        NULL, // 0x8d4
        NULL, // 0x8d5
        NULL, // 0x8d6
        NULL, // 0x8d7
        NULL, // 0x8d8
        NULL, // 0x8d9
        NULL, // 0x8da
        NULL, // 0x8db
        NULL, // 0x8dc
        NULL, // 0x8dd
        NULL, // 0x8de
        NULL, // 0x8df
        NULL, // 0x8e0
        NULL, // 0x8e1
        NULL, // 0x8e2
        NULL, // 0x8e3
        NULL, // 0x8e4
        NULL, // 0x8e5
        NULL, // 0x8e6
        NULL, // 0x8e7
        NULL, // 0x8e8
        NULL, // 0x8e9
        NULL, // 0x8ea
        NULL, // 0x8eb
        NULL, // 0x8ec
        NULL, // 0x8ed
        NULL, // 0x8ee
        NULL, // 0x8ef
        NULL, // 0x8f0
        NULL, // 0x8f1
        NULL, // 0x8f2
        NULL, // 0x8f3
        NULL, // 0x8f4
        NULL, // 0x8f5
        NULL, // 0x8f6
        NULL, // 0x8f7
        NULL, // 0x8f8
        NULL, // 0x8f9
        NULL, // 0x8fa
        NULL, // 0x8fb
        NULL, // 0x8fc
        NULL, // 0x8fd
        NULL, // 0x8fe
        NULL, // 0x8ff
        NULL, // 0x900
        NULL, // 0x901
        NULL, // 0x902
        NULL, // 0x903
        NULL, // 0x904
        NULL, // 0x905
        NULL, // 0x906
        NULL, // 0x907
        NULL, // 0x908
        NULL, // 0x909
        NULL, // 0x90a
        NULL, // 0x90b
        NULL, // 0x90c
        NULL, // 0x90d
        NULL, // 0x90e
        NULL, // 0x90f
        NULL, // 0x910
        NULL, // 0x911
        NULL, // 0x912
        NULL, // 0x913
        NULL, // 0x914
        NULL, // 0x915
        NULL, // 0x916
        NULL, // 0x917
        NULL, // 0x918
        NULL, // 0x919
        NULL, // 0x91a
        NULL, // 0x91b
        NULL, // 0x91c
        NULL, // 0x91d
        NULL, // 0x91e
        NULL, // 0x91f
        NULL, // 0x920
        NULL, // 0x921
        NULL, // 0x922
        NULL, // 0x923
        NULL, // 0x924
        NULL, // 0x925
        NULL, // 0x926
        NULL, // 0x927
        NULL, // 0x928
        NULL, // 0x929
        NULL, // 0x92a
        NULL, // 0x92b
        NULL, // 0x92c
        NULL, // 0x92d
        NULL, // 0x92e
        NULL, // 0x92f
        NULL, // 0x930
        NULL, // 0x931
        NULL, // 0x932
        NULL, // 0x933
        NULL, // 0x934
        NULL, // 0x935
        NULL, // 0x936
        NULL, // 0x937
        NULL, // 0x938
        NULL, // 0x939
        NULL, // 0x93a
        NULL, // 0x93b
        NULL, // 0x93c
        NULL, // 0x93d
        NULL, // 0x93e
        NULL, // 0x93f
        NULL, // 0x940
        NULL, // 0x941
        NULL, // 0x942
        NULL, // 0x943
        NULL, // 0x944
        NULL, // 0x945
        NULL, // 0x946
        NULL, // 0x947
        NULL, // 0x948
        NULL, // 0x949
        NULL, // 0x94a
        NULL, // 0x94b
        NULL, // 0x94c
        NULL, // 0x94d
        NULL, // 0x94e
        NULL, // 0x94f
        NULL, // 0x950
        NULL, // 0x951
        NULL, // 0x952
        NULL, // 0x953
        NULL, // 0x954
        NULL, // 0x955
        NULL, // 0x956
        NULL, // 0x957
        NULL, // 0x958
        NULL, // 0x959
        NULL, // 0x95a
        NULL, // 0x95b
        NULL, // 0x95c
        NULL, // 0x95d
        NULL, // 0x95e
        NULL, // 0x95f
        NULL, // 0x960
        NULL, // 0x961
        NULL, // 0x962
        NULL, // 0x963
        NULL, // 0x964
        NULL, // 0x965
        NULL, // 0x966
        NULL, // 0x967
        NULL, // 0x968
        NULL, // 0x969
        NULL, // 0x96a
        NULL, // 0x96b
        NULL, // 0x96c
        NULL, // 0x96d
        NULL, // 0x96e
        NULL, // 0x96f
        NULL, // 0x970
        NULL, // 0x971
        NULL, // 0x972
        NULL, // 0x973
        NULL, // 0x974
        NULL, // 0x975
        NULL, // 0x976
        NULL, // 0x977
        NULL, // 0x978
        NULL, // 0x979
        NULL, // 0x97a
        NULL, // 0x97b
        NULL, // 0x97c
        NULL, // 0x97d
        NULL, // 0x97e
        NULL, // 0x97f
        NULL, // 0x980
        NULL, // 0x981
        NULL, // 0x982
        NULL, // 0x983
        NULL, // 0x984
        NULL, // 0x985
        NULL, // 0x986
        NULL, // 0x987
        NULL, // 0x988
        NULL, // 0x989
        NULL, // 0x98a
        NULL, // 0x98b
        NULL, // 0x98c
        NULL, // 0x98d
        NULL, // 0x98e
        NULL, // 0x98f
        NULL, // 0x990
        NULL, // 0x991
        NULL, // 0x992
        NULL, // 0x993
        NULL, // 0x994
        NULL, // 0x995
        NULL, // 0x996
        NULL, // 0x997
        NULL, // 0x998
        NULL, // 0x999
        NULL, // 0x99a
        NULL, // 0x99b
        NULL, // 0x99c
        NULL, // 0x99d
        NULL, // 0x99e
        NULL, // 0x99f
        NULL, // 0x9a0
        NULL, // 0x9a1
        NULL, // 0x9a2
        NULL, // 0x9a3
        NULL, // 0x9a4
        NULL, // 0x9a5
        NULL, // 0x9a6
        NULL, // 0x9a7
        NULL, // 0x9a8
        NULL, // 0x9a9
        NULL, // 0x9aa
        NULL, // 0x9ab
        NULL, // 0x9ac
        NULL, // 0x9ad
        NULL, // 0x9ae
        NULL, // 0x9af
        NULL, // 0x9b0
        NULL, // 0x9b1
        NULL, // 0x9b2
        NULL, // 0x9b3
        NULL, // 0x9b4
        NULL, // 0x9b5
        NULL, // 0x9b6
        NULL, // 0x9b7
        NULL, // 0x9b8
        NULL, // 0x9b9
        NULL, // 0x9ba
        NULL, // 0x9bb
        NULL, // 0x9bc
        NULL, // 0x9bd
        NULL, // 0x9be
        NULL, // 0x9bf
        NULL, // 0x9c0
        NULL, // 0x9c1
        NULL, // 0x9c2
        NULL, // 0x9c3
        NULL, // 0x9c4
        NULL, // 0x9c5
        NULL, // 0x9c6
        NULL, // 0x9c7
        NULL, // 0x9c8
        NULL, // 0x9c9
        NULL, // 0x9ca
        NULL, // 0x9cb
        NULL, // 0x9cc
        NULL, // 0x9cd
        NULL, // 0x9ce
        NULL, // 0x9cf
        NULL, // 0x9d0
        NULL, // 0x9d1
        NULL, // 0x9d2
        NULL, // 0x9d3
        NULL, // 0x9d4
        NULL, // 0x9d5
        NULL, // 0x9d6
        NULL, // 0x9d7
        NULL, // 0x9d8
        NULL, // 0x9d9
        NULL, // 0x9da
        NULL, // 0x9db
        NULL, // 0x9dc
        NULL, // 0x9dd
        NULL, // 0x9de
        NULL, // 0x9df
        NULL, // 0x9e0
        NULL, // 0x9e1
        NULL, // 0x9e2
        NULL, // 0x9e3
        NULL, // 0x9e4
        NULL, // 0x9e5
        NULL, // 0x9e6
        NULL, // 0x9e7
        NULL, // 0x9e8
        NULL, // 0x9e9
        NULL, // 0x9ea
        NULL, // 0x9eb
        NULL, // 0x9ec
        NULL, // 0x9ed
        NULL, // 0x9ee
        NULL, // 0x9ef
        NULL, // 0x9f0
        NULL, // 0x9f1
        NULL, // 0x9f2
        NULL, // 0x9f3
        NULL, // 0x9f4
        NULL, // 0x9f5
        NULL, // 0x9f6
        NULL, // 0x9f7
        NULL, // 0x9f8
        NULL, // 0x9f9
        NULL, // 0x9fa
        NULL, // 0x9fb
        NULL, // 0x9fc
        NULL, // 0x9fd
        NULL, // 0x9fe
        NULL, // 0x9ff
        REP256(gbaemu::gba::cpu::impl::branch::b), // 0xa00
        REP256(gbaemu::gba::cpu::impl::branch::bl), // 0xb00
        NULL, // 0xc00
        NULL, // 0xc01
        NULL, // 0xc02
        NULL, // 0xc03
        NULL, // 0xc04
        NULL, // 0xc05
        NULL, // 0xc06
        NULL, // 0xc07
        NULL, // 0xc08
        NULL, // 0xc09
        NULL, // 0xc0a
        NULL, // 0xc0b
        NULL, // 0xc0c
        NULL, // 0xc0d
        NULL, // 0xc0e
        NULL, // 0xc0f
        NULL, // 0xc10
        NULL, // 0xc11
        NULL, // 0xc12
        NULL, // 0xc13
        NULL, // 0xc14
        NULL, // 0xc15
        NULL, // 0xc16
        NULL, // 0xc17
        NULL, // 0xc18
        NULL, // 0xc19
        NULL, // 0xc1a
        NULL, // 0xc1b
        NULL, // 0xc1c
        NULL, // 0xc1d
        NULL, // 0xc1e
        NULL, // 0xc1f
        NULL, // 0xc20
        NULL, // 0xc21
        NULL, // 0xc22
        NULL, // 0xc23
        NULL, // 0xc24
        NULL, // 0xc25
        NULL, // 0xc26
        NULL, // 0xc27
        NULL, // 0xc28
        NULL, // 0xc29
        NULL, // 0xc2a
        NULL, // 0xc2b
        NULL, // 0xc2c
        NULL, // 0xc2d
        NULL, // 0xc2e
        NULL, // 0xc2f
        NULL, // 0xc30
        NULL, // 0xc31
        NULL, // 0xc32
        NULL, // 0xc33
        NULL, // 0xc34
        NULL, // 0xc35
        NULL, // 0xc36
        NULL, // 0xc37
        NULL, // 0xc38
        NULL, // 0xc39
        NULL, // 0xc3a
        NULL, // 0xc3b
        NULL, // 0xc3c
        NULL, // 0xc3d
        NULL, // 0xc3e
        NULL, // 0xc3f
        NULL, // 0xc40
        NULL, // 0xc41
        NULL, // 0xc42
        NULL, // 0xc43
        NULL, // 0xc44
        NULL, // 0xc45
        NULL, // 0xc46
        NULL, // 0xc47
        NULL, // 0xc48
        NULL, // 0xc49
        NULL, // 0xc4a
        NULL, // 0xc4b
        NULL, // 0xc4c
        NULL, // 0xc4d
        NULL, // 0xc4e
        NULL, // 0xc4f
        NULL, // 0xc50
        NULL, // 0xc51
        NULL, // 0xc52
        NULL, // 0xc53
        NULL, // 0xc54
        NULL, // 0xc55
        NULL, // 0xc56
        NULL, // 0xc57
        NULL, // 0xc58
        NULL, // 0xc59
        NULL, // 0xc5a
        NULL, // 0xc5b
        NULL, // 0xc5c
        NULL, // 0xc5d
        NULL, // 0xc5e
        NULL, // 0xc5f
        NULL, // 0xc60
        NULL, // 0xc61
        NULL, // 0xc62
        NULL, // 0xc63
        NULL, // 0xc64
        NULL, // 0xc65
        NULL, // 0xc66
        NULL, // 0xc67
        NULL, // 0xc68
        NULL, // 0xc69
        NULL, // 0xc6a
        NULL, // 0xc6b
        NULL, // 0xc6c
        NULL, // 0xc6d
        NULL, // 0xc6e
        NULL, // 0xc6f
        NULL, // 0xc70
        NULL, // 0xc71
        NULL, // 0xc72
        NULL, // 0xc73
        NULL, // 0xc74
        NULL, // 0xc75
        NULL, // 0xc76
        NULL, // 0xc77
        NULL, // 0xc78
        NULL, // 0xc79
        NULL, // 0xc7a
        NULL, // 0xc7b
        NULL, // 0xc7c
        NULL, // 0xc7d
        NULL, // 0xc7e
        NULL, // 0xc7f
        NULL, // 0xc80
        NULL, // 0xc81
        NULL, // 0xc82
        NULL, // 0xc83
        NULL, // 0xc84
        NULL, // 0xc85
        NULL, // 0xc86
        NULL, // 0xc87
        NULL, // 0xc88
        NULL, // 0xc89
        NULL, // 0xc8a
        NULL, // 0xc8b
        NULL, // 0xc8c
        NULL, // 0xc8d
        NULL, // 0xc8e
        NULL, // 0xc8f
        NULL, // 0xc90
        NULL, // 0xc91
        NULL, // 0xc92
        NULL, // 0xc93
        NULL, // 0xc94
        NULL, // 0xc95
        NULL, // 0xc96
        NULL, // 0xc97
        NULL, // 0xc98
        NULL, // 0xc99
        NULL, // 0xc9a
        NULL, // 0xc9b
        NULL, // 0xc9c
        NULL, // 0xc9d
        NULL, // 0xc9e
        NULL, // 0xc9f
        NULL, // 0xca0
        NULL, // 0xca1
        NULL, // 0xca2
        NULL, // 0xca3
        NULL, // 0xca4
        NULL, // 0xca5
        NULL, // 0xca6
        NULL, // 0xca7
        NULL, // 0xca8
        NULL, // 0xca9
        NULL, // 0xcaa
        NULL, // 0xcab
        NULL, // 0xcac
        NULL, // 0xcad
        NULL, // 0xcae
        NULL, // 0xcaf
        NULL, // 0xcb0
        NULL, // 0xcb1
        NULL, // 0xcb2
        NULL, // 0xcb3
        NULL, // 0xcb4
        NULL, // 0xcb5
        NULL, // 0xcb6
        NULL, // 0xcb7
        NULL, // 0xcb8
        NULL, // 0xcb9
        NULL, // 0xcba
        NULL, // 0xcbb
        NULL, // 0xcbc
        NULL, // 0xcbd
        NULL, // 0xcbe
        NULL, // 0xcbf
        NULL, // 0xcc0
        NULL, // 0xcc1
        NULL, // 0xcc2
        NULL, // 0xcc3
        NULL, // 0xcc4
        NULL, // 0xcc5
        NULL, // 0xcc6
        NULL, // 0xcc7
        NULL, // 0xcc8
        NULL, // 0xcc9
        NULL, // 0xcca
        NULL, // 0xccb
        NULL, // 0xccc
        NULL, // 0xccd
        NULL, // 0xcce
        NULL, // 0xccf
        NULL, // 0xcd0
        NULL, // 0xcd1
        NULL, // 0xcd2
        NULL, // 0xcd3
        NULL, // 0xcd4
        NULL, // 0xcd5
        NULL, // 0xcd6
        NULL, // 0xcd7
        NULL, // 0xcd8
        NULL, // 0xcd9
        NULL, // 0xcda
        NULL, // 0xcdb
        NULL, // 0xcdc
        NULL, // 0xcdd
        NULL, // 0xcde
        NULL, // 0xcdf
        NULL, // 0xce0
        NULL, // 0xce1
        NULL, // 0xce2
        NULL, // 0xce3
        NULL, // 0xce4
        NULL, // 0xce5
        NULL, // 0xce6
        NULL, // 0xce7
        NULL, // 0xce8
        NULL, // 0xce9
        NULL, // 0xcea
        NULL, // 0xceb
        NULL, // 0xcec
        NULL, // 0xced
        NULL, // 0xcee
        NULL, // 0xcef
        NULL, // 0xcf0
        NULL, // 0xcf1
        NULL, // 0xcf2
        NULL, // 0xcf3
        NULL, // 0xcf4
        NULL, // 0xcf5
        NULL, // 0xcf6
        NULL, // 0xcf7
        NULL, // 0xcf8
        NULL, // 0xcf9
        NULL, // 0xcfa
        NULL, // 0xcfb
        NULL, // 0xcfc
        NULL, // 0xcfd
        NULL, // 0xcfe
        NULL, // 0xcff
        NULL, // 0xd00
        NULL, // 0xd01
        NULL, // 0xd02
        NULL, // 0xd03
        NULL, // 0xd04
        NULL, // 0xd05
        NULL, // 0xd06
        NULL, // 0xd07
        NULL, // 0xd08
        NULL, // 0xd09
        NULL, // 0xd0a
        NULL, // 0xd0b
        NULL, // 0xd0c
        NULL, // 0xd0d
        NULL, // 0xd0e
        NULL, // 0xd0f
        NULL, // 0xd10
        NULL, // 0xd11
        NULL, // 0xd12
        NULL, // 0xd13
        NULL, // 0xd14
        NULL, // 0xd15
        NULL, // 0xd16
        NULL, // 0xd17
        NULL, // 0xd18
        NULL, // 0xd19
        NULL, // 0xd1a
        NULL, // 0xd1b
        NULL, // 0xd1c
        NULL, // 0xd1d
        NULL, // 0xd1e
        NULL, // 0xd1f
        NULL, // 0xd20
        NULL, // 0xd21
        NULL, // 0xd22
        NULL, // 0xd23
        NULL, // 0xd24
        NULL, // 0xd25
        NULL, // 0xd26
        NULL, // 0xd27
        NULL, // 0xd28
        NULL, // 0xd29
        NULL, // 0xd2a
        NULL, // 0xd2b
        NULL, // 0xd2c
        NULL, // 0xd2d
        NULL, // 0xd2e
        NULL, // 0xd2f
        NULL, // 0xd30
        NULL, // 0xd31
        NULL, // 0xd32
        NULL, // 0xd33
        NULL, // 0xd34
        NULL, // 0xd35
        NULL, // 0xd36
        NULL, // 0xd37
        NULL, // 0xd38
        NULL, // 0xd39
        NULL, // 0xd3a
        NULL, // 0xd3b
        NULL, // 0xd3c
        NULL, // 0xd3d
        NULL, // 0xd3e
        NULL, // 0xd3f
        NULL, // 0xd40
        NULL, // 0xd41
        NULL, // 0xd42
        NULL, // 0xd43
        NULL, // 0xd44
        NULL, // 0xd45
        NULL, // 0xd46
        NULL, // 0xd47
        NULL, // 0xd48
        NULL, // 0xd49
        NULL, // 0xd4a
        NULL, // 0xd4b
        NULL, // 0xd4c
        NULL, // 0xd4d
        NULL, // 0xd4e
        NULL, // 0xd4f
        NULL, // 0xd50
        NULL, // 0xd51
        NULL, // 0xd52
        NULL, // 0xd53
        NULL, // 0xd54
        NULL, // 0xd55
        NULL, // 0xd56
        NULL, // 0xd57
        NULL, // 0xd58
        NULL, // 0xd59
        NULL, // 0xd5a
        NULL, // 0xd5b
        NULL, // 0xd5c
        NULL, // 0xd5d
        NULL, // 0xd5e
        NULL, // 0xd5f
        NULL, // 0xd60
        NULL, // 0xd61
        NULL, // 0xd62
        NULL, // 0xd63
        NULL, // 0xd64
        NULL, // 0xd65
        NULL, // 0xd66
        NULL, // 0xd67
        NULL, // 0xd68
        NULL, // 0xd69
        NULL, // 0xd6a
        NULL, // 0xd6b
        NULL, // 0xd6c
        NULL, // 0xd6d
        NULL, // 0xd6e
        NULL, // 0xd6f
        NULL, // 0xd70
        NULL, // 0xd71
        NULL, // 0xd72
        NULL, // 0xd73
        NULL, // 0xd74
        NULL, // 0xd75
        NULL, // 0xd76
        NULL, // 0xd77
        NULL, // 0xd78
        NULL, // 0xd79
        NULL, // 0xd7a
        NULL, // 0xd7b
        NULL, // 0xd7c
        NULL, // 0xd7d
        NULL, // 0xd7e
        NULL, // 0xd7f
        NULL, // 0xd80
        NULL, // 0xd81
        NULL, // 0xd82
        NULL, // 0xd83
        NULL, // 0xd84
        NULL, // 0xd85
        NULL, // 0xd86
        NULL, // 0xd87
        NULL, // 0xd88
        NULL, // 0xd89
        NULL, // 0xd8a
        NULL, // 0xd8b
        NULL, // 0xd8c
        NULL, // 0xd8d
        NULL, // 0xd8e
        NULL, // 0xd8f
        NULL, // 0xd90
        NULL, // 0xd91
        NULL, // 0xd92
        NULL, // 0xd93
        NULL, // 0xd94
        NULL, // 0xd95
        NULL, // 0xd96
        NULL, // 0xd97
        NULL, // 0xd98
        NULL, // 0xd99
        NULL, // 0xd9a
        NULL, // 0xd9b
        NULL, // 0xd9c
        NULL, // 0xd9d
        NULL, // 0xd9e
        NULL, // 0xd9f
        NULL, // 0xda0
        NULL, // 0xda1
        NULL, // 0xda2
        NULL, // 0xda3
        NULL, // 0xda4
        NULL, // 0xda5
        NULL, // 0xda6
        NULL, // 0xda7
        NULL, // 0xda8
        NULL, // 0xda9
        NULL, // 0xdaa
        NULL, // 0xdab
        NULL, // 0xdac
        NULL, // 0xdad
        NULL, // 0xdae
        NULL, // 0xdaf
        NULL, // 0xdb0
        NULL, // 0xdb1
        NULL, // 0xdb2
        NULL, // 0xdb3
        NULL, // 0xdb4
        NULL, // 0xdb5
        NULL, // 0xdb6
        NULL, // 0xdb7
        NULL, // 0xdb8
        NULL, // 0xdb9
        NULL, // 0xdba
        NULL, // 0xdbb
        NULL, // 0xdbc
        NULL, // 0xdbd
        NULL, // 0xdbe
        NULL, // 0xdbf
        NULL, // 0xdc0
        NULL, // 0xdc1
        NULL, // 0xdc2
        NULL, // 0xdc3
        NULL, // 0xdc4
        NULL, // 0xdc5
        NULL, // 0xdc6
        NULL, // 0xdc7
        NULL, // 0xdc8
        NULL, // 0xdc9
        NULL, // 0xdca
        NULL, // 0xdcb
        NULL, // 0xdcc
        NULL, // 0xdcd
        NULL, // 0xdce
        NULL, // 0xdcf
        NULL, // 0xdd0
        NULL, // 0xdd1
        NULL, // 0xdd2
        NULL, // 0xdd3
        NULL, // 0xdd4
        NULL, // 0xdd5
        NULL, // 0xdd6
        NULL, // 0xdd7
        NULL, // 0xdd8
        NULL, // 0xdd9
        NULL, // 0xdda
        NULL, // 0xddb
        NULL, // 0xddc
        NULL, // 0xddd
        NULL, // 0xdde
        NULL, // 0xddf
        NULL, // 0xde0
        NULL, // 0xde1
        NULL, // 0xde2
        NULL, // 0xde3
        NULL, // 0xde4
        NULL, // 0xde5
        NULL, // 0xde6
        NULL, // 0xde7
        NULL, // 0xde8
        NULL, // 0xde9
        NULL, // 0xdea
        NULL, // 0xdeb
        NULL, // 0xdec
        NULL, // 0xded
        NULL, // 0xdee
        NULL, // 0xdef
        NULL, // 0xdf0
        NULL, // 0xdf1
        NULL, // 0xdf2
        NULL, // 0xdf3
        NULL, // 0xdf4
        NULL, // 0xdf5
        NULL, // 0xdf6
        NULL, // 0xdf7
        NULL, // 0xdf8
        NULL, // 0xdf9
        NULL, // 0xdfa
        NULL, // 0xdfb
        NULL, // 0xdfc
        NULL, // 0xdfd
        NULL, // 0xdfe
        NULL, // 0xdff
        NULL, // 0xe00
        NULL, // 0xe01
        NULL, // 0xe02
        NULL, // 0xe03
        NULL, // 0xe04
        NULL, // 0xe05
        NULL, // 0xe06
        NULL, // 0xe07
        NULL, // 0xe08
        NULL, // 0xe09
        NULL, // 0xe0a
        NULL, // 0xe0b
        NULL, // 0xe0c
        NULL, // 0xe0d
        NULL, // 0xe0e
        NULL, // 0xe0f
        NULL, // 0xe10
        NULL, // 0xe11
        NULL, // 0xe12
        NULL, // 0xe13
        NULL, // 0xe14
        NULL, // 0xe15
        NULL, // 0xe16
        NULL, // 0xe17
        NULL, // 0xe18
        NULL, // 0xe19
        NULL, // 0xe1a
        NULL, // 0xe1b
        NULL, // 0xe1c
        NULL, // 0xe1d
        NULL, // 0xe1e
        NULL, // 0xe1f
        NULL, // 0xe20
        NULL, // 0xe21
        NULL, // 0xe22
        NULL, // 0xe23
        NULL, // 0xe24
        NULL, // 0xe25
        NULL, // 0xe26
        NULL, // 0xe27
        NULL, // 0xe28
        NULL, // 0xe29
        NULL, // 0xe2a
        NULL, // 0xe2b
        NULL, // 0xe2c
        NULL, // 0xe2d
        NULL, // 0xe2e
        NULL, // 0xe2f
        NULL, // 0xe30
        NULL, // 0xe31
        NULL, // 0xe32
        NULL, // 0xe33
        NULL, // 0xe34
        NULL, // 0xe35
        NULL, // 0xe36
        NULL, // 0xe37
        NULL, // 0xe38
        NULL, // 0xe39
        NULL, // 0xe3a
        NULL, // 0xe3b
        NULL, // 0xe3c
        NULL, // 0xe3d
        NULL, // 0xe3e
        NULL, // 0xe3f
        NULL, // 0xe40
        NULL, // 0xe41
        NULL, // 0xe42
        NULL, // 0xe43
        NULL, // 0xe44
        NULL, // 0xe45
        NULL, // 0xe46
        NULL, // 0xe47
        NULL, // 0xe48
        NULL, // 0xe49
        NULL, // 0xe4a
        NULL, // 0xe4b
        NULL, // 0xe4c
        NULL, // 0xe4d
        NULL, // 0xe4e
        NULL, // 0xe4f
        NULL, // 0xe50
        NULL, // 0xe51
        NULL, // 0xe52
        NULL, // 0xe53
        NULL, // 0xe54
        NULL, // 0xe55
        NULL, // 0xe56
        NULL, // 0xe57
        NULL, // 0xe58
        NULL, // 0xe59
        NULL, // 0xe5a
        NULL, // 0xe5b
        NULL, // 0xe5c
        NULL, // 0xe5d
        NULL, // 0xe5e
        NULL, // 0xe5f
        NULL, // 0xe60
        NULL, // 0xe61
        NULL, // 0xe62
        NULL, // 0xe63
        NULL, // 0xe64
        NULL, // 0xe65
        NULL, // 0xe66
        NULL, // 0xe67
        NULL, // 0xe68
        NULL, // 0xe69
        NULL, // 0xe6a
        NULL, // 0xe6b
        NULL, // 0xe6c
        NULL, // 0xe6d
        NULL, // 0xe6e
        NULL, // 0xe6f
        NULL, // 0xe70
        NULL, // 0xe71
        NULL, // 0xe72
        NULL, // 0xe73
        NULL, // 0xe74
        NULL, // 0xe75
        NULL, // 0xe76
        NULL, // 0xe77
        NULL, // 0xe78
        NULL, // 0xe79
        NULL, // 0xe7a
        NULL, // 0xe7b
        NULL, // 0xe7c
        NULL, // 0xe7d
        NULL, // 0xe7e
        NULL, // 0xe7f
        NULL, // 0xe80
        NULL, // 0xe81
        NULL, // 0xe82
        NULL, // 0xe83
        NULL, // 0xe84
        NULL, // 0xe85
        NULL, // 0xe86
        NULL, // 0xe87
        NULL, // 0xe88
        NULL, // 0xe89
        NULL, // 0xe8a
        NULL, // 0xe8b
        NULL, // 0xe8c
        NULL, // 0xe8d
        NULL, // 0xe8e
        NULL, // 0xe8f
        NULL, // 0xe90
        NULL, // 0xe91
        NULL, // 0xe92
        NULL, // 0xe93
        NULL, // 0xe94
        NULL, // 0xe95
        NULL, // 0xe96
        NULL, // 0xe97
        NULL, // 0xe98
        NULL, // 0xe99
        NULL, // 0xe9a
        NULL, // 0xe9b
        NULL, // 0xe9c
        NULL, // 0xe9d
        NULL, // 0xe9e
        NULL, // 0xe9f
        NULL, // 0xea0
        NULL, // 0xea1
        NULL, // 0xea2
        NULL, // 0xea3
        NULL, // 0xea4
        NULL, // 0xea5
        NULL, // 0xea6
        NULL, // 0xea7
        NULL, // 0xea8
        NULL, // 0xea9
        NULL, // 0xeaa
        NULL, // 0xeab
        NULL, // 0xeac
        NULL, // 0xead
        NULL, // 0xeae
        NULL, // 0xeaf
        NULL, // 0xeb0
        NULL, // 0xeb1
        NULL, // 0xeb2
        NULL, // 0xeb3
        NULL, // 0xeb4
        NULL, // 0xeb5
        NULL, // 0xeb6
        NULL, // 0xeb7
        NULL, // 0xeb8
        NULL, // 0xeb9
        NULL, // 0xeba
        NULL, // 0xebb
        NULL, // 0xebc
        NULL, // 0xebd
        NULL, // 0xebe
        NULL, // 0xebf
        NULL, // 0xec0
        NULL, // 0xec1
        NULL, // 0xec2
        NULL, // 0xec3
        NULL, // 0xec4
        NULL, // 0xec5
        NULL, // 0xec6
        NULL, // 0xec7
        NULL, // 0xec8
        NULL, // 0xec9
        NULL, // 0xeca
        NULL, // 0xecb
        NULL, // 0xecc
        NULL, // 0xecd
        NULL, // 0xece
        NULL, // 0xecf
        NULL, // 0xed0
        NULL, // 0xed1
        NULL, // 0xed2
        NULL, // 0xed3
        NULL, // 0xed4
        NULL, // 0xed5
        NULL, // 0xed6
        NULL, // 0xed7
        NULL, // 0xed8
        NULL, // 0xed9
        NULL, // 0xeda
        NULL, // 0xedb
        NULL, // 0xedc
        NULL, // 0xedd
        NULL, // 0xede
        NULL, // 0xedf
        NULL, // 0xee0
        NULL, // 0xee1
        NULL, // 0xee2
        NULL, // 0xee3
        NULL, // 0xee4
        NULL, // 0xee5
        NULL, // 0xee6
        NULL, // 0xee7
        NULL, // 0xee8
        NULL, // 0xee9
        NULL, // 0xeea
        NULL, // 0xeeb
        NULL, // 0xeec
        NULL, // 0xeed
        NULL, // 0xeee
        NULL, // 0xeef
        NULL, // 0xef0
        NULL, // 0xef1
        NULL, // 0xef2
        NULL, // 0xef3
        NULL, // 0xef4
        NULL, // 0xef5
        NULL, // 0xef6
        NULL, // 0xef7
        NULL, // 0xef8
        NULL, // 0xef9
        NULL, // 0xefa
        NULL, // 0xefb
        NULL, // 0xefc
        NULL, // 0xefd
        NULL, // 0xefe
        NULL, // 0xeff
        REP256(gbaemu::gba::cpu::impl::swi::swi) // 0xf00
    };

    instruction_t decode(uint32_t opcode) {
        return {
            opcode,
            opcodeDecoderTable[((opcode >> 16) & 0xff0) | ((opcode >> 4) & 0xf)]
        };
    }
}
