#ifndef __INCLUDE_CORE_CPU_OP_THUMB_MOVECOMPAREADDSUBTRACTIMMEDIATE_H__
#define __INCLUDE_CORE_CPU_OP_THUMB_MOVECOMPAREADDSUBTRACTIMMEDIATE_H__

#include <stdint.h>

void cpuOpcodeThumbMoveCompareAddSubtractImmediate(uint16_t p_opcode);

#endif
