#ifndef __INCLUDE_CORE_CPU_OP_THUMB_LOADSTORESIGNEXTENDEDBYTEHALFWORD_H__
#define __INCLUDE_CORE_CPU_OP_THUMB_LOADSTORESIGNEXTENDEDBYTEHALFWORD_H__

#include <stdint.h>

void cpuOpcodeThumbLoadStoreSignExtendedByteHalfword(uint16_t p_opcode);

#endif
